templateDir: ./sdk-resources
files:
  package.mustache:
    templateType: SupportingFiles
    destinationFilename: package.json
npmName: plexjs
npmRepository: lukehagar
npmVersion: 0.0.1
useSingleRequestParameter: true