/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  Device,
  Device$inboundSchema,
  Device$Outbound,
  Device$outboundSchema,
} from "./device.js";

/**
 * `MediaContainer` is the root element of most Plex API responses. It serves as a generic container for various types of content (Metadata, Hubs, Directories, etc.) and includes pagination information (offset, size, totalSize) when applicable.
 *
 * @remarks
 * Common attributes: - identifier: Unique identifier for this container - size: Number of items in this response page - totalSize: Total number of items available (for pagination) - offset: Starting index of this page (for pagination)
 * The container often "hoists" common attributes from its children. For example, if all tracks in a container share the same album title, the `parentTitle` attribute may appear on the MediaContainer rather than being repeated on each track.
 */
export type DvrRequestHandlerSlashGetResponses200MediaContainerMediaContainer =
  {
    identifier?: string | undefined;
    /**
     * The offset of where this container page starts among the total objects available. Also provided in the `X-Plex-Container-Start` header.
     *
     * @remarks
     */
    offset?: number | undefined;
    size?: number | undefined;
    /**
     * The total size of objects available. Also provided in the `X-Plex-Container-Total-Size` header.
     *
     * @remarks
     */
    totalSize?: number | undefined;
    /**
     * A status indicator. If present and non-zero, indicates an error
     */
    status?: number | undefined;
  };

export type Dvr = {
  device?: Array<Device> | undefined;
  key?: string | undefined;
  language?: string | undefined;
  lineup?: string | undefined;
  uuid?: string | undefined;
};

export type DvrRequestHandlerSlashGetResponses200MediaContainer = {
  mediaContainer?:
    | DvrRequestHandlerSlashGetResponses200MediaContainerMediaContainer
    | undefined;
  dvr?: Array<Dvr> | undefined;
};

/**
 * OK
 */
export type DvrRequestHandlerSlashGetResponses200 = {
  mediaContainer?:
    | DvrRequestHandlerSlashGetResponses200MediaContainer
    | undefined;
};

/** @internal */
export const DvrRequestHandlerSlashGetResponses200MediaContainerMediaContainer$inboundSchema:
  z.ZodType<
    DvrRequestHandlerSlashGetResponses200MediaContainerMediaContainer,
    z.ZodTypeDef,
    unknown
  > = z.object({
    identifier: z.string().optional(),
    offset: z.number().int().optional(),
    size: z.number().int().optional(),
    totalSize: z.number().int().optional(),
    status: z.number().int().optional(),
  });

/** @internal */
export type DvrRequestHandlerSlashGetResponses200MediaContainerMediaContainer$Outbound =
  {
    identifier?: string | undefined;
    offset?: number | undefined;
    size?: number | undefined;
    totalSize?: number | undefined;
    status?: number | undefined;
  };

/** @internal */
export const DvrRequestHandlerSlashGetResponses200MediaContainerMediaContainer$outboundSchema:
  z.ZodType<
    DvrRequestHandlerSlashGetResponses200MediaContainerMediaContainer$Outbound,
    z.ZodTypeDef,
    DvrRequestHandlerSlashGetResponses200MediaContainerMediaContainer
  > = z.object({
    identifier: z.string().optional(),
    offset: z.number().int().optional(),
    size: z.number().int().optional(),
    totalSize: z.number().int().optional(),
    status: z.number().int().optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DvrRequestHandlerSlashGetResponses200MediaContainerMediaContainer$ {
  /** @deprecated use `DvrRequestHandlerSlashGetResponses200MediaContainerMediaContainer$inboundSchema` instead. */
  export const inboundSchema =
    DvrRequestHandlerSlashGetResponses200MediaContainerMediaContainer$inboundSchema;
  /** @deprecated use `DvrRequestHandlerSlashGetResponses200MediaContainerMediaContainer$outboundSchema` instead. */
  export const outboundSchema =
    DvrRequestHandlerSlashGetResponses200MediaContainerMediaContainer$outboundSchema;
  /** @deprecated use `DvrRequestHandlerSlashGetResponses200MediaContainerMediaContainer$Outbound` instead. */
  export type Outbound =
    DvrRequestHandlerSlashGetResponses200MediaContainerMediaContainer$Outbound;
}

export function dvrRequestHandlerSlashGetResponses200MediaContainerMediaContainerToJSON(
  dvrRequestHandlerSlashGetResponses200MediaContainerMediaContainer:
    DvrRequestHandlerSlashGetResponses200MediaContainerMediaContainer,
): string {
  return JSON.stringify(
    DvrRequestHandlerSlashGetResponses200MediaContainerMediaContainer$outboundSchema
      .parse(dvrRequestHandlerSlashGetResponses200MediaContainerMediaContainer),
  );
}

export function dvrRequestHandlerSlashGetResponses200MediaContainerMediaContainerFromJSON(
  jsonString: string,
): SafeParseResult<
  DvrRequestHandlerSlashGetResponses200MediaContainerMediaContainer,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DvrRequestHandlerSlashGetResponses200MediaContainerMediaContainer$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'DvrRequestHandlerSlashGetResponses200MediaContainerMediaContainer' from JSON`,
  );
}

/** @internal */
export const Dvr$inboundSchema: z.ZodType<Dvr, z.ZodTypeDef, unknown> = z
  .object({
    Device: z.array(Device$inboundSchema).optional(),
    key: z.string().optional(),
    language: z.string().optional(),
    lineup: z.string().optional(),
    uuid: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      "Device": "device",
    });
  });

/** @internal */
export type Dvr$Outbound = {
  Device?: Array<Device$Outbound> | undefined;
  key?: string | undefined;
  language?: string | undefined;
  lineup?: string | undefined;
  uuid?: string | undefined;
};

/** @internal */
export const Dvr$outboundSchema: z.ZodType<Dvr$Outbound, z.ZodTypeDef, Dvr> = z
  .object({
    device: z.array(Device$outboundSchema).optional(),
    key: z.string().optional(),
    language: z.string().optional(),
    lineup: z.string().optional(),
    uuid: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      device: "Device",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Dvr$ {
  /** @deprecated use `Dvr$inboundSchema` instead. */
  export const inboundSchema = Dvr$inboundSchema;
  /** @deprecated use `Dvr$outboundSchema` instead. */
  export const outboundSchema = Dvr$outboundSchema;
  /** @deprecated use `Dvr$Outbound` instead. */
  export type Outbound = Dvr$Outbound;
}

export function dvrToJSON(dvr: Dvr): string {
  return JSON.stringify(Dvr$outboundSchema.parse(dvr));
}

export function dvrFromJSON(
  jsonString: string,
): SafeParseResult<Dvr, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Dvr$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Dvr' from JSON`,
  );
}

/** @internal */
export const DvrRequestHandlerSlashGetResponses200MediaContainer$inboundSchema:
  z.ZodType<
    DvrRequestHandlerSlashGetResponses200MediaContainer,
    z.ZodTypeDef,
    unknown
  > = z.object({
    MediaContainer: z.lazy(() =>
      DvrRequestHandlerSlashGetResponses200MediaContainerMediaContainer$inboundSchema
    ).optional(),
    DVR: z.array(z.lazy(() => Dvr$inboundSchema)).optional(),
  }).transform((v) => {
    return remap$(v, {
      "MediaContainer": "mediaContainer",
      "DVR": "dvr",
    });
  });

/** @internal */
export type DvrRequestHandlerSlashGetResponses200MediaContainer$Outbound = {
  MediaContainer?:
    | DvrRequestHandlerSlashGetResponses200MediaContainerMediaContainer$Outbound
    | undefined;
  DVR?: Array<Dvr$Outbound> | undefined;
};

/** @internal */
export const DvrRequestHandlerSlashGetResponses200MediaContainer$outboundSchema:
  z.ZodType<
    DvrRequestHandlerSlashGetResponses200MediaContainer$Outbound,
    z.ZodTypeDef,
    DvrRequestHandlerSlashGetResponses200MediaContainer
  > = z.object({
    mediaContainer: z.lazy(() =>
      DvrRequestHandlerSlashGetResponses200MediaContainerMediaContainer$outboundSchema
    ).optional(),
    dvr: z.array(z.lazy(() => Dvr$outboundSchema)).optional(),
  }).transform((v) => {
    return remap$(v, {
      mediaContainer: "MediaContainer",
      dvr: "DVR",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DvrRequestHandlerSlashGetResponses200MediaContainer$ {
  /** @deprecated use `DvrRequestHandlerSlashGetResponses200MediaContainer$inboundSchema` instead. */
  export const inboundSchema =
    DvrRequestHandlerSlashGetResponses200MediaContainer$inboundSchema;
  /** @deprecated use `DvrRequestHandlerSlashGetResponses200MediaContainer$outboundSchema` instead. */
  export const outboundSchema =
    DvrRequestHandlerSlashGetResponses200MediaContainer$outboundSchema;
  /** @deprecated use `DvrRequestHandlerSlashGetResponses200MediaContainer$Outbound` instead. */
  export type Outbound =
    DvrRequestHandlerSlashGetResponses200MediaContainer$Outbound;
}

export function dvrRequestHandlerSlashGetResponses200MediaContainerToJSON(
  dvrRequestHandlerSlashGetResponses200MediaContainer:
    DvrRequestHandlerSlashGetResponses200MediaContainer,
): string {
  return JSON.stringify(
    DvrRequestHandlerSlashGetResponses200MediaContainer$outboundSchema.parse(
      dvrRequestHandlerSlashGetResponses200MediaContainer,
    ),
  );
}

export function dvrRequestHandlerSlashGetResponses200MediaContainerFromJSON(
  jsonString: string,
): SafeParseResult<
  DvrRequestHandlerSlashGetResponses200MediaContainer,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DvrRequestHandlerSlashGetResponses200MediaContainer$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'DvrRequestHandlerSlashGetResponses200MediaContainer' from JSON`,
  );
}

/** @internal */
export const DvrRequestHandlerSlashGetResponses200$inboundSchema: z.ZodType<
  DvrRequestHandlerSlashGetResponses200,
  z.ZodTypeDef,
  unknown
> = z.object({
  MediaContainer: z.lazy(() =>
    DvrRequestHandlerSlashGetResponses200MediaContainer$inboundSchema
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    "MediaContainer": "mediaContainer",
  });
});

/** @internal */
export type DvrRequestHandlerSlashGetResponses200$Outbound = {
  MediaContainer?:
    | DvrRequestHandlerSlashGetResponses200MediaContainer$Outbound
    | undefined;
};

/** @internal */
export const DvrRequestHandlerSlashGetResponses200$outboundSchema: z.ZodType<
  DvrRequestHandlerSlashGetResponses200$Outbound,
  z.ZodTypeDef,
  DvrRequestHandlerSlashGetResponses200
> = z.object({
  mediaContainer: z.lazy(() =>
    DvrRequestHandlerSlashGetResponses200MediaContainer$outboundSchema
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    mediaContainer: "MediaContainer",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DvrRequestHandlerSlashGetResponses200$ {
  /** @deprecated use `DvrRequestHandlerSlashGetResponses200$inboundSchema` instead. */
  export const inboundSchema =
    DvrRequestHandlerSlashGetResponses200$inboundSchema;
  /** @deprecated use `DvrRequestHandlerSlashGetResponses200$outboundSchema` instead. */
  export const outboundSchema =
    DvrRequestHandlerSlashGetResponses200$outboundSchema;
  /** @deprecated use `DvrRequestHandlerSlashGetResponses200$Outbound` instead. */
  export type Outbound = DvrRequestHandlerSlashGetResponses200$Outbound;
}

export function dvrRequestHandlerSlashGetResponses200ToJSON(
  dvrRequestHandlerSlashGetResponses200: DvrRequestHandlerSlashGetResponses200,
): string {
  return JSON.stringify(
    DvrRequestHandlerSlashGetResponses200$outboundSchema.parse(
      dvrRequestHandlerSlashGetResponses200,
    ),
  );
}

export function dvrRequestHandlerSlashGetResponses200FromJSON(
  jsonString: string,
): SafeParseResult<DvrRequestHandlerSlashGetResponses200, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      DvrRequestHandlerSlashGetResponses200$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DvrRequestHandlerSlashGetResponses200' from JSON`,
  );
}
