/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export enum LocationParameter {
  Lan = "lan",
  Wan = "wan",
  Cellular = "cellular",
}

/** @internal */
export const LocationParameter$outboundSchema: z.ZodNativeEnum<
  typeof LocationParameter
> = z.nativeEnum(LocationParameter);
