/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../../lib/primitives.js";
import * as z from "zod";

export type EnablePaperTrailErrors = {
    code?: number | undefined;
    message?: string | undefined;
    status?: number | undefined;
};

/**
 * Unauthorized - Returned if the X-Plex-Token is missing from the header or query.
 */
export type EnablePaperTrailResponseBodyData = {
    errors?: Array<EnablePaperTrailErrors> | undefined;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse?: Response | undefined;
};

/**
 * Unauthorized - Returned if the X-Plex-Token is missing from the header or query.
 */
export class EnablePaperTrailResponseBody extends Error {
    errors?: Array<EnablePaperTrailErrors> | undefined;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse?: Response | undefined;

    /** The original data that was passed to this error instance. */
    data$: EnablePaperTrailResponseBodyData;

    constructor(err: EnablePaperTrailResponseBodyData) {
        const message =
            "message" in err && typeof err.message === "string"
                ? err.message
                : `API error occurred: ${JSON.stringify(err)}`;
        super(message);
        this.data$ = err;

        if (err.errors != null) {
            this.errors = err.errors;
        }
        if (err.rawResponse != null) {
            this.rawResponse = err.rawResponse;
        }

        this.name = "EnablePaperTrailResponseBody";
    }
}

/** @internal */
export const EnablePaperTrailErrors$inboundSchema: z.ZodType<
    EnablePaperTrailErrors,
    z.ZodTypeDef,
    unknown
> = z.object({
    code: z.number().optional(),
    message: z.string().optional(),
    status: z.number().optional(),
});

/** @internal */
export type EnablePaperTrailErrors$Outbound = {
    code?: number | undefined;
    message?: string | undefined;
    status?: number | undefined;
};

/** @internal */
export const EnablePaperTrailErrors$outboundSchema: z.ZodType<
    EnablePaperTrailErrors$Outbound,
    z.ZodTypeDef,
    EnablePaperTrailErrors
> = z.object({
    code: z.number().optional(),
    message: z.string().optional(),
    status: z.number().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EnablePaperTrailErrors$ {
    /** @deprecated use `EnablePaperTrailErrors$inboundSchema` instead. */
    export const inboundSchema = EnablePaperTrailErrors$inboundSchema;
    /** @deprecated use `EnablePaperTrailErrors$outboundSchema` instead. */
    export const outboundSchema = EnablePaperTrailErrors$outboundSchema;
    /** @deprecated use `EnablePaperTrailErrors$Outbound` instead. */
    export type Outbound = EnablePaperTrailErrors$Outbound;
}

/** @internal */
export const EnablePaperTrailResponseBody$inboundSchema: z.ZodType<
    EnablePaperTrailResponseBody,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        errors: z.array(z.lazy(() => EnablePaperTrailErrors$inboundSchema)).optional(),
        RawResponse: z.instanceof(Response).optional(),
    })
    .transform((v) => {
        const remapped = remap$(v, {
            RawResponse: "rawResponse",
        });

        return new EnablePaperTrailResponseBody(remapped);
    });

/** @internal */
export type EnablePaperTrailResponseBody$Outbound = {
    errors?: Array<EnablePaperTrailErrors$Outbound> | undefined;
    RawResponse?: never | undefined;
};

/** @internal */
export const EnablePaperTrailResponseBody$outboundSchema: z.ZodType<
    EnablePaperTrailResponseBody$Outbound,
    z.ZodTypeDef,
    EnablePaperTrailResponseBody
> = z
    .instanceof(EnablePaperTrailResponseBody)
    .transform((v) => v.data$)
    .pipe(
        z
            .object({
                errors: z.array(z.lazy(() => EnablePaperTrailErrors$outboundSchema)).optional(),
                rawResponse: z
                    .instanceof(Response)
                    .transform(() => {
                        throw new Error("Response cannot be serialized");
                    })
                    .optional(),
            })
            .transform((v) => {
                return remap$(v, {
                    rawResponse: "RawResponse",
                });
            })
    );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EnablePaperTrailResponseBody$ {
    /** @deprecated use `EnablePaperTrailResponseBody$inboundSchema` instead. */
    export const inboundSchema = EnablePaperTrailResponseBody$inboundSchema;
    /** @deprecated use `EnablePaperTrailResponseBody$outboundSchema` instead. */
    export const outboundSchema = EnablePaperTrailResponseBody$outboundSchema;
    /** @deprecated use `EnablePaperTrailResponseBody$Outbound` instead. */
    export type Outbound = EnablePaperTrailResponseBody$Outbound;
}
