/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../../lib/primitives.js";
import * as z from "zod";

export type StartUniversalTranscodeErrors = {
    code?: number | undefined;
    message?: string | undefined;
    status?: number | undefined;
};

/**
 * Unauthorized - Returned if the X-Plex-Token is missing from the header or query.
 */
export type StartUniversalTranscodeResponseBodyData = {
    errors?: Array<StartUniversalTranscodeErrors> | undefined;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse?: Response | undefined;
};

/**
 * Unauthorized - Returned if the X-Plex-Token is missing from the header or query.
 */
export class StartUniversalTranscodeResponseBody extends Error {
    errors?: Array<StartUniversalTranscodeErrors> | undefined;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse?: Response | undefined;

    /** The original data that was passed to this error instance. */
    data$: StartUniversalTranscodeResponseBodyData;

    constructor(err: StartUniversalTranscodeResponseBodyData) {
        const message =
            "message" in err && typeof err.message === "string"
                ? err.message
                : `API error occurred: ${JSON.stringify(err)}`;
        super(message);
        this.data$ = err;

        if (err.errors != null) {
            this.errors = err.errors;
        }
        if (err.rawResponse != null) {
            this.rawResponse = err.rawResponse;
        }

        this.name = "StartUniversalTranscodeResponseBody";
    }
}

/** @internal */
export const StartUniversalTranscodeErrors$inboundSchema: z.ZodType<
    StartUniversalTranscodeErrors,
    z.ZodTypeDef,
    unknown
> = z.object({
    code: z.number().optional(),
    message: z.string().optional(),
    status: z.number().optional(),
});

/** @internal */
export type StartUniversalTranscodeErrors$Outbound = {
    code?: number | undefined;
    message?: string | undefined;
    status?: number | undefined;
};

/** @internal */
export const StartUniversalTranscodeErrors$outboundSchema: z.ZodType<
    StartUniversalTranscodeErrors$Outbound,
    z.ZodTypeDef,
    StartUniversalTranscodeErrors
> = z.object({
    code: z.number().optional(),
    message: z.string().optional(),
    status: z.number().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace StartUniversalTranscodeErrors$ {
    /** @deprecated use `StartUniversalTranscodeErrors$inboundSchema` instead. */
    export const inboundSchema = StartUniversalTranscodeErrors$inboundSchema;
    /** @deprecated use `StartUniversalTranscodeErrors$outboundSchema` instead. */
    export const outboundSchema = StartUniversalTranscodeErrors$outboundSchema;
    /** @deprecated use `StartUniversalTranscodeErrors$Outbound` instead. */
    export type Outbound = StartUniversalTranscodeErrors$Outbound;
}

/** @internal */
export const StartUniversalTranscodeResponseBody$inboundSchema: z.ZodType<
    StartUniversalTranscodeResponseBody,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        errors: z.array(z.lazy(() => StartUniversalTranscodeErrors$inboundSchema)).optional(),
        RawResponse: z.instanceof(Response).optional(),
    })
    .transform((v) => {
        const remapped = remap$(v, {
            RawResponse: "rawResponse",
        });

        return new StartUniversalTranscodeResponseBody(remapped);
    });

/** @internal */
export type StartUniversalTranscodeResponseBody$Outbound = {
    errors?: Array<StartUniversalTranscodeErrors$Outbound> | undefined;
    RawResponse?: never | undefined;
};

/** @internal */
export const StartUniversalTranscodeResponseBody$outboundSchema: z.ZodType<
    StartUniversalTranscodeResponseBody$Outbound,
    z.ZodTypeDef,
    StartUniversalTranscodeResponseBody
> = z
    .instanceof(StartUniversalTranscodeResponseBody)
    .transform((v) => v.data$)
    .pipe(
        z
            .object({
                errors: z
                    .array(z.lazy(() => StartUniversalTranscodeErrors$outboundSchema))
                    .optional(),
                rawResponse: z
                    .instanceof(Response)
                    .transform(() => {
                        throw new Error("Response cannot be serialized");
                    })
                    .optional(),
            })
            .transform((v) => {
                return remap$(v, {
                    rawResponse: "RawResponse",
                });
            })
    );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace StartUniversalTranscodeResponseBody$ {
    /** @deprecated use `StartUniversalTranscodeResponseBody$inboundSchema` instead. */
    export const inboundSchema = StartUniversalTranscodeResponseBody$inboundSchema;
    /** @deprecated use `StartUniversalTranscodeResponseBody$outboundSchema` instead. */
    export const outboundSchema = StartUniversalTranscodeResponseBody$outboundSchema;
    /** @deprecated use `StartUniversalTranscodeResponseBody$Outbound` instead. */
    export type Outbound = StartUniversalTranscodeResponseBody$Outbound;
}
