/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../../lib/primitives.js";
import * as z from "zod";

export type UpdatePlayProgressErrors = {
    code?: number | undefined;
    message?: string | undefined;
    status?: number | undefined;
};

/**
 * Unauthorized - Returned if the X-Plex-Token is missing from the header or query.
 */
export type UpdatePlayProgressResponseBodyData = {
    errors?: Array<UpdatePlayProgressErrors> | undefined;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse?: Response | undefined;
};

/**
 * Unauthorized - Returned if the X-Plex-Token is missing from the header or query.
 */
export class UpdatePlayProgressResponseBody extends Error {
    errors?: Array<UpdatePlayProgressErrors> | undefined;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse?: Response | undefined;

    /** The original data that was passed to this error instance. */
    data$: UpdatePlayProgressResponseBodyData;

    constructor(err: UpdatePlayProgressResponseBodyData) {
        const message =
            "message" in err && typeof err.message === "string"
                ? err.message
                : `API error occurred: ${JSON.stringify(err)}`;
        super(message);
        this.data$ = err;

        if (err.errors != null) {
            this.errors = err.errors;
        }
        if (err.rawResponse != null) {
            this.rawResponse = err.rawResponse;
        }

        this.name = "UpdatePlayProgressResponseBody";
    }
}

/** @internal */
export const UpdatePlayProgressErrors$inboundSchema: z.ZodType<
    UpdatePlayProgressErrors,
    z.ZodTypeDef,
    unknown
> = z.object({
    code: z.number().optional(),
    message: z.string().optional(),
    status: z.number().optional(),
});

/** @internal */
export type UpdatePlayProgressErrors$Outbound = {
    code?: number | undefined;
    message?: string | undefined;
    status?: number | undefined;
};

/** @internal */
export const UpdatePlayProgressErrors$outboundSchema: z.ZodType<
    UpdatePlayProgressErrors$Outbound,
    z.ZodTypeDef,
    UpdatePlayProgressErrors
> = z.object({
    code: z.number().optional(),
    message: z.string().optional(),
    status: z.number().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdatePlayProgressErrors$ {
    /** @deprecated use `UpdatePlayProgressErrors$inboundSchema` instead. */
    export const inboundSchema = UpdatePlayProgressErrors$inboundSchema;
    /** @deprecated use `UpdatePlayProgressErrors$outboundSchema` instead. */
    export const outboundSchema = UpdatePlayProgressErrors$outboundSchema;
    /** @deprecated use `UpdatePlayProgressErrors$Outbound` instead. */
    export type Outbound = UpdatePlayProgressErrors$Outbound;
}

/** @internal */
export const UpdatePlayProgressResponseBody$inboundSchema: z.ZodType<
    UpdatePlayProgressResponseBody,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        errors: z.array(z.lazy(() => UpdatePlayProgressErrors$inboundSchema)).optional(),
        RawResponse: z.instanceof(Response).optional(),
    })
    .transform((v) => {
        const remapped = remap$(v, {
            RawResponse: "rawResponse",
        });

        return new UpdatePlayProgressResponseBody(remapped);
    });

/** @internal */
export type UpdatePlayProgressResponseBody$Outbound = {
    errors?: Array<UpdatePlayProgressErrors$Outbound> | undefined;
    RawResponse?: never | undefined;
};

/** @internal */
export const UpdatePlayProgressResponseBody$outboundSchema: z.ZodType<
    UpdatePlayProgressResponseBody$Outbound,
    z.ZodTypeDef,
    UpdatePlayProgressResponseBody
> = z
    .instanceof(UpdatePlayProgressResponseBody)
    .transform((v) => v.data$)
    .pipe(
        z
            .object({
                errors: z.array(z.lazy(() => UpdatePlayProgressErrors$outboundSchema)).optional(),
                rawResponse: z
                    .instanceof(Response)
                    .transform(() => {
                        throw new Error("Response cannot be serialized");
                    })
                    .optional(),
            })
            .transform((v) => {
                return remap$(v, {
                    rawResponse: "RawResponse",
                });
            })
    );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdatePlayProgressResponseBody$ {
    /** @deprecated use `UpdatePlayProgressResponseBody$inboundSchema` instead. */
    export const inboundSchema = UpdatePlayProgressResponseBody$inboundSchema;
    /** @deprecated use `UpdatePlayProgressResponseBody$outboundSchema` instead. */
    export const outboundSchema = UpdatePlayProgressResponseBody$outboundSchema;
    /** @deprecated use `UpdatePlayProgressResponseBody$Outbound` instead. */
    export type Outbound = UpdatePlayProgressResponseBody$Outbound;
}
