templateDir: ./sdk-resources/plextv-resources
files:
  package.mustache:
    templateType: SupportingFiles
    destinationFilename: package.json
npmName: plexjs
npmRepository: lukehagar
npmVersion: 0.0.29
useSingleRequestParameter: true
sortParamsByRequiredFlag: true
gitUserID: lukehagar
gitRepoID: plexjs
