/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type DeleteHistoryGlobals = {
  /**
   * An opaque identifier unique to the client
   */
  xPlexClientIdentifier?: string | undefined;
  /**
   * The name of the client product
   */
  xPlexProduct?: string | undefined;
  /**
   * The version of the client application
   */
  xPlexVersion?: string | undefined;
  /**
   * The platform of the client
   */
  xPlexPlatform?: string | undefined;
  /**
   * The version of the platform
   */
  xPlexPlatformVersion?: string | undefined;
  /**
   * A relatively friendly name for the client device
   */
  xPlexDevice?: string | undefined;
  /**
   * A potentially less friendly identifier for the device model
   */
  xPlexModel?: string | undefined;
  /**
   * The device vendor
   */
  xPlexDeviceVendor?: string | undefined;
  /**
   * A friendly name for the client
   */
  xPlexDeviceName?: string | undefined;
  /**
   * The marketplace on which the client application is distributed
   */
  xPlexMarketplace?: string | undefined;
};

export type DeleteHistoryRequest = {
  /**
   * An opaque identifier unique to the client
   */
  xPlexClientIdentifier?: string | undefined;
  /**
   * The name of the client product
   */
  xPlexProduct?: string | undefined;
  /**
   * The version of the client application
   */
  xPlexVersion?: string | undefined;
  /**
   * The platform of the client
   */
  xPlexPlatform?: string | undefined;
  /**
   * The version of the platform
   */
  xPlexPlatformVersion?: string | undefined;
  /**
   * A relatively friendly name for the client device
   */
  xPlexDevice?: string | undefined;
  /**
   * A potentially less friendly identifier for the device model
   */
  xPlexModel?: string | undefined;
  /**
   * The device vendor
   */
  xPlexDeviceVendor?: string | undefined;
  /**
   * A friendly name for the client
   */
  xPlexDeviceName?: string | undefined;
  /**
   * The marketplace on which the client application is distributed
   */
  xPlexMarketplace?: string | undefined;
  /**
   * The id of the history item (the `historyKey` from above)
   */
  historyId: number;
};

export type DeleteHistoryResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * OK
   */
  mediaContainer?: shared.MediaContainer | undefined;
  headers: { [k: string]: Array<string> };
};

/** @internal */
export const DeleteHistoryGlobals$inboundSchema: z.ZodType<
  DeleteHistoryGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  "X-Plex-Client-Identifier": z.string().optional(),
  "X-Plex-Product": z.string().optional(),
  "X-Plex-Version": z.string().optional(),
  "X-Plex-Platform": z.string().optional(),
  "X-Plex-Platform-Version": z.string().optional(),
  "X-Plex-Device": z.string().optional(),
  "X-Plex-Model": z.string().optional(),
  "X-Plex-Device-Vendor": z.string().optional(),
  "X-Plex-Device-Name": z.string().optional(),
  "X-Plex-Marketplace": z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "X-Plex-Client-Identifier": "xPlexClientIdentifier",
    "X-Plex-Product": "xPlexProduct",
    "X-Plex-Version": "xPlexVersion",
    "X-Plex-Platform": "xPlexPlatform",
    "X-Plex-Platform-Version": "xPlexPlatformVersion",
    "X-Plex-Device": "xPlexDevice",
    "X-Plex-Model": "xPlexModel",
    "X-Plex-Device-Vendor": "xPlexDeviceVendor",
    "X-Plex-Device-Name": "xPlexDeviceName",
    "X-Plex-Marketplace": "xPlexMarketplace",
  });
});

/** @internal */
export type DeleteHistoryGlobals$Outbound = {
  "X-Plex-Client-Identifier"?: string | undefined;
  "X-Plex-Product"?: string | undefined;
  "X-Plex-Version"?: string | undefined;
  "X-Plex-Platform"?: string | undefined;
  "X-Plex-Platform-Version"?: string | undefined;
  "X-Plex-Device"?: string | undefined;
  "X-Plex-Model"?: string | undefined;
  "X-Plex-Device-Vendor"?: string | undefined;
  "X-Plex-Device-Name"?: string | undefined;
  "X-Plex-Marketplace"?: string | undefined;
};

/** @internal */
export const DeleteHistoryGlobals$outboundSchema: z.ZodType<
  DeleteHistoryGlobals$Outbound,
  z.ZodTypeDef,
  DeleteHistoryGlobals
> = z.object({
  xPlexClientIdentifier: z.string().optional(),
  xPlexProduct: z.string().optional(),
  xPlexVersion: z.string().optional(),
  xPlexPlatform: z.string().optional(),
  xPlexPlatformVersion: z.string().optional(),
  xPlexDevice: z.string().optional(),
  xPlexModel: z.string().optional(),
  xPlexDeviceVendor: z.string().optional(),
  xPlexDeviceName: z.string().optional(),
  xPlexMarketplace: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    xPlexClientIdentifier: "X-Plex-Client-Identifier",
    xPlexProduct: "X-Plex-Product",
    xPlexVersion: "X-Plex-Version",
    xPlexPlatform: "X-Plex-Platform",
    xPlexPlatformVersion: "X-Plex-Platform-Version",
    xPlexDevice: "X-Plex-Device",
    xPlexModel: "X-Plex-Model",
    xPlexDeviceVendor: "X-Plex-Device-Vendor",
    xPlexDeviceName: "X-Plex-Device-Name",
    xPlexMarketplace: "X-Plex-Marketplace",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteHistoryGlobals$ {
  /** @deprecated use `DeleteHistoryGlobals$inboundSchema` instead. */
  export const inboundSchema = DeleteHistoryGlobals$inboundSchema;
  /** @deprecated use `DeleteHistoryGlobals$outboundSchema` instead. */
  export const outboundSchema = DeleteHistoryGlobals$outboundSchema;
  /** @deprecated use `DeleteHistoryGlobals$Outbound` instead. */
  export type Outbound = DeleteHistoryGlobals$Outbound;
}

export function deleteHistoryGlobalsToJSON(
  deleteHistoryGlobals: DeleteHistoryGlobals,
): string {
  return JSON.stringify(
    DeleteHistoryGlobals$outboundSchema.parse(deleteHistoryGlobals),
  );
}

export function deleteHistoryGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<DeleteHistoryGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteHistoryGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteHistoryGlobals' from JSON`,
  );
}

/** @internal */
export const DeleteHistoryRequest$inboundSchema: z.ZodType<
  DeleteHistoryRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  "X-Plex-Client-Identifier": z.string().optional(),
  "X-Plex-Product": z.string().optional(),
  "X-Plex-Version": z.string().optional(),
  "X-Plex-Platform": z.string().optional(),
  "X-Plex-Platform-Version": z.string().optional(),
  "X-Plex-Device": z.string().optional(),
  "X-Plex-Model": z.string().optional(),
  "X-Plex-Device-Vendor": z.string().optional(),
  "X-Plex-Device-Name": z.string().optional(),
  "X-Plex-Marketplace": z.string().optional(),
  historyId: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "X-Plex-Client-Identifier": "xPlexClientIdentifier",
    "X-Plex-Product": "xPlexProduct",
    "X-Plex-Version": "xPlexVersion",
    "X-Plex-Platform": "xPlexPlatform",
    "X-Plex-Platform-Version": "xPlexPlatformVersion",
    "X-Plex-Device": "xPlexDevice",
    "X-Plex-Model": "xPlexModel",
    "X-Plex-Device-Vendor": "xPlexDeviceVendor",
    "X-Plex-Device-Name": "xPlexDeviceName",
    "X-Plex-Marketplace": "xPlexMarketplace",
  });
});

/** @internal */
export type DeleteHistoryRequest$Outbound = {
  "X-Plex-Client-Identifier"?: string | undefined;
  "X-Plex-Product"?: string | undefined;
  "X-Plex-Version"?: string | undefined;
  "X-Plex-Platform"?: string | undefined;
  "X-Plex-Platform-Version"?: string | undefined;
  "X-Plex-Device"?: string | undefined;
  "X-Plex-Model"?: string | undefined;
  "X-Plex-Device-Vendor"?: string | undefined;
  "X-Plex-Device-Name"?: string | undefined;
  "X-Plex-Marketplace"?: string | undefined;
  historyId: number;
};

/** @internal */
export const DeleteHistoryRequest$outboundSchema: z.ZodType<
  DeleteHistoryRequest$Outbound,
  z.ZodTypeDef,
  DeleteHistoryRequest
> = z.object({
  xPlexClientIdentifier: z.string().optional(),
  xPlexProduct: z.string().optional(),
  xPlexVersion: z.string().optional(),
  xPlexPlatform: z.string().optional(),
  xPlexPlatformVersion: z.string().optional(),
  xPlexDevice: z.string().optional(),
  xPlexModel: z.string().optional(),
  xPlexDeviceVendor: z.string().optional(),
  xPlexDeviceName: z.string().optional(),
  xPlexMarketplace: z.string().optional(),
  historyId: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    xPlexClientIdentifier: "X-Plex-Client-Identifier",
    xPlexProduct: "X-Plex-Product",
    xPlexVersion: "X-Plex-Version",
    xPlexPlatform: "X-Plex-Platform",
    xPlexPlatformVersion: "X-Plex-Platform-Version",
    xPlexDevice: "X-Plex-Device",
    xPlexModel: "X-Plex-Model",
    xPlexDeviceVendor: "X-Plex-Device-Vendor",
    xPlexDeviceName: "X-Plex-Device-Name",
    xPlexMarketplace: "X-Plex-Marketplace",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteHistoryRequest$ {
  /** @deprecated use `DeleteHistoryRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteHistoryRequest$inboundSchema;
  /** @deprecated use `DeleteHistoryRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteHistoryRequest$outboundSchema;
  /** @deprecated use `DeleteHistoryRequest$Outbound` instead. */
  export type Outbound = DeleteHistoryRequest$Outbound;
}

export function deleteHistoryRequestToJSON(
  deleteHistoryRequest: DeleteHistoryRequest,
): string {
  return JSON.stringify(
    DeleteHistoryRequest$outboundSchema.parse(deleteHistoryRequest),
  );
}

export function deleteHistoryRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteHistoryRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteHistoryRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteHistoryRequest' from JSON`,
  );
}

/** @internal */
export const DeleteHistoryResponse$inboundSchema: z.ZodType<
  DeleteHistoryResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
  MediaContainer: shared.MediaContainer$inboundSchema.optional(),
  Headers: z.record(z.array(z.string())),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
    "MediaContainer": "mediaContainer",
    "Headers": "headers",
  });
});

/** @internal */
export type DeleteHistoryResponse$Outbound = {
  ContentType: string;
  StatusCode: number;
  RawResponse: never;
  MediaContainer?: shared.MediaContainer$Outbound | undefined;
  Headers: { [k: string]: Array<string> };
};

/** @internal */
export const DeleteHistoryResponse$outboundSchema: z.ZodType<
  DeleteHistoryResponse$Outbound,
  z.ZodTypeDef,
  DeleteHistoryResponse
> = z.object({
  contentType: z.string(),
  statusCode: z.number().int(),
  rawResponse: z.instanceof(Response).transform(() => {
    throw new Error("Response cannot be serialized");
  }),
  mediaContainer: shared.MediaContainer$outboundSchema.optional(),
  headers: z.record(z.array(z.string())),
}).transform((v) => {
  return remap$(v, {
    contentType: "ContentType",
    statusCode: "StatusCode",
    rawResponse: "RawResponse",
    mediaContainer: "MediaContainer",
    headers: "Headers",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteHistoryResponse$ {
  /** @deprecated use `DeleteHistoryResponse$inboundSchema` instead. */
  export const inboundSchema = DeleteHistoryResponse$inboundSchema;
  /** @deprecated use `DeleteHistoryResponse$outboundSchema` instead. */
  export const outboundSchema = DeleteHistoryResponse$outboundSchema;
  /** @deprecated use `DeleteHistoryResponse$Outbound` instead. */
  export type Outbound = DeleteHistoryResponse$Outbound;
}

export function deleteHistoryResponseToJSON(
  deleteHistoryResponse: DeleteHistoryResponse,
): string {
  return JSON.stringify(
    DeleteHistoryResponse$outboundSchema.parse(deleteHistoryResponse),
  );
}

export function deleteHistoryResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteHistoryResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteHistoryResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteHistoryResponse' from JSON`,
  );
}
