/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type DetectCreditsGlobals = {
  /**
   * An opaque identifier unique to the client
   */
  xPlexClientIdentifier?: string | undefined;
  /**
   * The name of the client product
   */
  xPlexProduct?: string | undefined;
  /**
   * The version of the client application
   */
  xPlexVersion?: string | undefined;
  /**
   * The platform of the client
   */
  xPlexPlatform?: string | undefined;
  /**
   * The version of the platform
   */
  xPlexPlatformVersion?: string | undefined;
  /**
   * A relatively friendly name for the client device
   */
  xPlexDevice?: string | undefined;
  /**
   * A potentially less friendly identifier for the device model
   */
  xPlexModel?: string | undefined;
  /**
   * The device vendor
   */
  xPlexDeviceVendor?: string | undefined;
  /**
   * A friendly name for the client
   */
  xPlexDeviceName?: string | undefined;
  /**
   * The marketplace on which the client application is distributed
   */
  xPlexMarketplace?: string | undefined;
};

export type DetectCreditsRequest = {
  /**
   * An opaque identifier unique to the client
   */
  xPlexClientIdentifier?: string | undefined;
  /**
   * The name of the client product
   */
  xPlexProduct?: string | undefined;
  /**
   * The version of the client application
   */
  xPlexVersion?: string | undefined;
  /**
   * The platform of the client
   */
  xPlexPlatform?: string | undefined;
  /**
   * The version of the platform
   */
  xPlexPlatformVersion?: string | undefined;
  /**
   * A relatively friendly name for the client device
   */
  xPlexDevice?: string | undefined;
  /**
   * A potentially less friendly identifier for the device model
   */
  xPlexModel?: string | undefined;
  /**
   * The device vendor
   */
  xPlexDeviceVendor?: string | undefined;
  /**
   * A friendly name for the client
   */
  xPlexDeviceName?: string | undefined;
  /**
   * The marketplace on which the client application is distributed
   */
  xPlexMarketplace?: string | undefined;
  ids: string;
  force?: shared.BoolInt | undefined;
  manual?: shared.BoolInt | undefined;
};

export type DetectCreditsResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
};

/** @internal */
export const DetectCreditsGlobals$inboundSchema: z.ZodType<
  DetectCreditsGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  "X-Plex-Client-Identifier": z.string().optional(),
  "X-Plex-Product": z.string().optional(),
  "X-Plex-Version": z.string().optional(),
  "X-Plex-Platform": z.string().optional(),
  "X-Plex-Platform-Version": z.string().optional(),
  "X-Plex-Device": z.string().optional(),
  "X-Plex-Model": z.string().optional(),
  "X-Plex-Device-Vendor": z.string().optional(),
  "X-Plex-Device-Name": z.string().optional(),
  "X-Plex-Marketplace": z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "X-Plex-Client-Identifier": "xPlexClientIdentifier",
    "X-Plex-Product": "xPlexProduct",
    "X-Plex-Version": "xPlexVersion",
    "X-Plex-Platform": "xPlexPlatform",
    "X-Plex-Platform-Version": "xPlexPlatformVersion",
    "X-Plex-Device": "xPlexDevice",
    "X-Plex-Model": "xPlexModel",
    "X-Plex-Device-Vendor": "xPlexDeviceVendor",
    "X-Plex-Device-Name": "xPlexDeviceName",
    "X-Plex-Marketplace": "xPlexMarketplace",
  });
});

/** @internal */
export type DetectCreditsGlobals$Outbound = {
  "X-Plex-Client-Identifier"?: string | undefined;
  "X-Plex-Product"?: string | undefined;
  "X-Plex-Version"?: string | undefined;
  "X-Plex-Platform"?: string | undefined;
  "X-Plex-Platform-Version"?: string | undefined;
  "X-Plex-Device"?: string | undefined;
  "X-Plex-Model"?: string | undefined;
  "X-Plex-Device-Vendor"?: string | undefined;
  "X-Plex-Device-Name"?: string | undefined;
  "X-Plex-Marketplace"?: string | undefined;
};

/** @internal */
export const DetectCreditsGlobals$outboundSchema: z.ZodType<
  DetectCreditsGlobals$Outbound,
  z.ZodTypeDef,
  DetectCreditsGlobals
> = z.object({
  xPlexClientIdentifier: z.string().optional(),
  xPlexProduct: z.string().optional(),
  xPlexVersion: z.string().optional(),
  xPlexPlatform: z.string().optional(),
  xPlexPlatformVersion: z.string().optional(),
  xPlexDevice: z.string().optional(),
  xPlexModel: z.string().optional(),
  xPlexDeviceVendor: z.string().optional(),
  xPlexDeviceName: z.string().optional(),
  xPlexMarketplace: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    xPlexClientIdentifier: "X-Plex-Client-Identifier",
    xPlexProduct: "X-Plex-Product",
    xPlexVersion: "X-Plex-Version",
    xPlexPlatform: "X-Plex-Platform",
    xPlexPlatformVersion: "X-Plex-Platform-Version",
    xPlexDevice: "X-Plex-Device",
    xPlexModel: "X-Plex-Model",
    xPlexDeviceVendor: "X-Plex-Device-Vendor",
    xPlexDeviceName: "X-Plex-Device-Name",
    xPlexMarketplace: "X-Plex-Marketplace",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DetectCreditsGlobals$ {
  /** @deprecated use `DetectCreditsGlobals$inboundSchema` instead. */
  export const inboundSchema = DetectCreditsGlobals$inboundSchema;
  /** @deprecated use `DetectCreditsGlobals$outboundSchema` instead. */
  export const outboundSchema = DetectCreditsGlobals$outboundSchema;
  /** @deprecated use `DetectCreditsGlobals$Outbound` instead. */
  export type Outbound = DetectCreditsGlobals$Outbound;
}

export function detectCreditsGlobalsToJSON(
  detectCreditsGlobals: DetectCreditsGlobals,
): string {
  return JSON.stringify(
    DetectCreditsGlobals$outboundSchema.parse(detectCreditsGlobals),
  );
}

export function detectCreditsGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<DetectCreditsGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DetectCreditsGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DetectCreditsGlobals' from JSON`,
  );
}

/** @internal */
export const DetectCreditsRequest$inboundSchema: z.ZodType<
  DetectCreditsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  "X-Plex-Client-Identifier": z.string().optional(),
  "X-Plex-Product": z.string().optional(),
  "X-Plex-Version": z.string().optional(),
  "X-Plex-Platform": z.string().optional(),
  "X-Plex-Platform-Version": z.string().optional(),
  "X-Plex-Device": z.string().optional(),
  "X-Plex-Model": z.string().optional(),
  "X-Plex-Device-Vendor": z.string().optional(),
  "X-Plex-Device-Name": z.string().optional(),
  "X-Plex-Marketplace": z.string().optional(),
  ids: z.string(),
  force: shared.BoolInt$inboundSchema.optional(),
  manual: shared.BoolInt$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "X-Plex-Client-Identifier": "xPlexClientIdentifier",
    "X-Plex-Product": "xPlexProduct",
    "X-Plex-Version": "xPlexVersion",
    "X-Plex-Platform": "xPlexPlatform",
    "X-Plex-Platform-Version": "xPlexPlatformVersion",
    "X-Plex-Device": "xPlexDevice",
    "X-Plex-Model": "xPlexModel",
    "X-Plex-Device-Vendor": "xPlexDeviceVendor",
    "X-Plex-Device-Name": "xPlexDeviceName",
    "X-Plex-Marketplace": "xPlexMarketplace",
  });
});

/** @internal */
export type DetectCreditsRequest$Outbound = {
  "X-Plex-Client-Identifier"?: string | undefined;
  "X-Plex-Product"?: string | undefined;
  "X-Plex-Version"?: string | undefined;
  "X-Plex-Platform"?: string | undefined;
  "X-Plex-Platform-Version"?: string | undefined;
  "X-Plex-Device"?: string | undefined;
  "X-Plex-Model"?: string | undefined;
  "X-Plex-Device-Vendor"?: string | undefined;
  "X-Plex-Device-Name"?: string | undefined;
  "X-Plex-Marketplace"?: string | undefined;
  ids: string;
  force?: number | undefined;
  manual?: number | undefined;
};

/** @internal */
export const DetectCreditsRequest$outboundSchema: z.ZodType<
  DetectCreditsRequest$Outbound,
  z.ZodTypeDef,
  DetectCreditsRequest
> = z.object({
  xPlexClientIdentifier: z.string().optional(),
  xPlexProduct: z.string().optional(),
  xPlexVersion: z.string().optional(),
  xPlexPlatform: z.string().optional(),
  xPlexPlatformVersion: z.string().optional(),
  xPlexDevice: z.string().optional(),
  xPlexModel: z.string().optional(),
  xPlexDeviceVendor: z.string().optional(),
  xPlexDeviceName: z.string().optional(),
  xPlexMarketplace: z.string().optional(),
  ids: z.string(),
  force: shared.BoolInt$outboundSchema.optional(),
  manual: shared.BoolInt$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    xPlexClientIdentifier: "X-Plex-Client-Identifier",
    xPlexProduct: "X-Plex-Product",
    xPlexVersion: "X-Plex-Version",
    xPlexPlatform: "X-Plex-Platform",
    xPlexPlatformVersion: "X-Plex-Platform-Version",
    xPlexDevice: "X-Plex-Device",
    xPlexModel: "X-Plex-Model",
    xPlexDeviceVendor: "X-Plex-Device-Vendor",
    xPlexDeviceName: "X-Plex-Device-Name",
    xPlexMarketplace: "X-Plex-Marketplace",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DetectCreditsRequest$ {
  /** @deprecated use `DetectCreditsRequest$inboundSchema` instead. */
  export const inboundSchema = DetectCreditsRequest$inboundSchema;
  /** @deprecated use `DetectCreditsRequest$outboundSchema` instead. */
  export const outboundSchema = DetectCreditsRequest$outboundSchema;
  /** @deprecated use `DetectCreditsRequest$Outbound` instead. */
  export type Outbound = DetectCreditsRequest$Outbound;
}

export function detectCreditsRequestToJSON(
  detectCreditsRequest: DetectCreditsRequest,
): string {
  return JSON.stringify(
    DetectCreditsRequest$outboundSchema.parse(detectCreditsRequest),
  );
}

export function detectCreditsRequestFromJSON(
  jsonString: string,
): SafeParseResult<DetectCreditsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DetectCreditsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DetectCreditsRequest' from JSON`,
  );
}

/** @internal */
export const DetectCreditsResponse$inboundSchema: z.ZodType<
  DetectCreditsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
  });
});

/** @internal */
export type DetectCreditsResponse$Outbound = {
  ContentType: string;
  StatusCode: number;
  RawResponse: never;
};

/** @internal */
export const DetectCreditsResponse$outboundSchema: z.ZodType<
  DetectCreditsResponse$Outbound,
  z.ZodTypeDef,
  DetectCreditsResponse
> = z.object({
  contentType: z.string(),
  statusCode: z.number().int(),
  rawResponse: z.instanceof(Response).transform(() => {
    throw new Error("Response cannot be serialized");
  }),
}).transform((v) => {
  return remap$(v, {
    contentType: "ContentType",
    statusCode: "StatusCode",
    rawResponse: "RawResponse",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DetectCreditsResponse$ {
  /** @deprecated use `DetectCreditsResponse$inboundSchema` instead. */
  export const inboundSchema = DetectCreditsResponse$inboundSchema;
  /** @deprecated use `DetectCreditsResponse$outboundSchema` instead. */
  export const outboundSchema = DetectCreditsResponse$outboundSchema;
  /** @deprecated use `DetectCreditsResponse$Outbound` instead. */
  export type Outbound = DetectCreditsResponse$Outbound;
}

export function detectCreditsResponseToJSON(
  detectCreditsResponse: DetectCreditsResponse,
): string {
  return JSON.stringify(
    DetectCreditsResponse$outboundSchema.parse(detectCreditsResponse),
  );
}

export function detectCreditsResponseFromJSON(
  jsonString: string,
): SafeParseResult<DetectCreditsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DetectCreditsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DetectCreditsResponse' from JSON`,
  );
}
