/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type DetectCreditsGlobals = {
  /**
   * Indicates the client accepts the indicated media types
   */
  accepts?: shared.Accepts | undefined;
  /**
   * An opaque identifier unique to the client
   */
  clientIdentifier?: string | undefined;
  /**
   * The name of the client product
   */
  product?: string | undefined;
  /**
   * The version of the client application
   */
  version?: string | undefined;
  /**
   * The platform of the client
   */
  platform?: string | undefined;
  /**
   * The version of the platform
   */
  platformVersion?: string | undefined;
  /**
   * A relatively friendly name for the client device
   */
  device?: string | undefined;
  /**
   * A potentially less friendly identifier for the device model
   */
  model?: string | undefined;
  /**
   * The device vendor
   */
  deviceVendor?: string | undefined;
  /**
   * A friendly name for the client
   */
  deviceName?: string | undefined;
  /**
   * The marketplace on which the client application is distributed
   */
  marketplace?: string | undefined;
};

export type DetectCreditsRequest = {
  /**
   * Indicates the client accepts the indicated media types
   */
  accepts?: shared.Accepts | undefined;
  /**
   * An opaque identifier unique to the client
   */
  clientIdentifier?: string | undefined;
  /**
   * The name of the client product
   */
  product?: string | undefined;
  /**
   * The version of the client application
   */
  version?: string | undefined;
  /**
   * The platform of the client
   */
  platform?: string | undefined;
  /**
   * The version of the platform
   */
  platformVersion?: string | undefined;
  /**
   * A relatively friendly name for the client device
   */
  device?: string | undefined;
  /**
   * A potentially less friendly identifier for the device model
   */
  model?: string | undefined;
  /**
   * The device vendor
   */
  deviceVendor?: string | undefined;
  /**
   * A friendly name for the client
   */
  deviceName?: string | undefined;
  /**
   * The marketplace on which the client application is distributed
   */
  marketplace?: string | undefined;
  ids: string;
  force?: shared.BoolInt | undefined;
  manual?: shared.BoolInt | undefined;
};

export type DetectCreditsResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
};

/** @internal */
export const DetectCreditsGlobals$inboundSchema: z.ZodType<
  DetectCreditsGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  accepts: shared.Accepts$inboundSchema.default(shared.Accepts.ApplicationXml),
  "Client-Identifier": z.string().optional(),
  Product: z.string().optional(),
  Version: z.string().optional(),
  Platform: z.string().optional(),
  "Platform-Version": z.string().optional(),
  Device: z.string().optional(),
  Model: z.string().optional(),
  "Device-Vendor": z.string().optional(),
  "Device-Name": z.string().optional(),
  Marketplace: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "Client-Identifier": "clientIdentifier",
    "Product": "product",
    "Version": "version",
    "Platform": "platform",
    "Platform-Version": "platformVersion",
    "Device": "device",
    "Model": "model",
    "Device-Vendor": "deviceVendor",
    "Device-Name": "deviceName",
    "Marketplace": "marketplace",
  });
});

/** @internal */
export type DetectCreditsGlobals$Outbound = {
  accepts: string;
  "Client-Identifier"?: string | undefined;
  Product?: string | undefined;
  Version?: string | undefined;
  Platform?: string | undefined;
  "Platform-Version"?: string | undefined;
  Device?: string | undefined;
  Model?: string | undefined;
  "Device-Vendor"?: string | undefined;
  "Device-Name"?: string | undefined;
  Marketplace?: string | undefined;
};

/** @internal */
export const DetectCreditsGlobals$outboundSchema: z.ZodType<
  DetectCreditsGlobals$Outbound,
  z.ZodTypeDef,
  DetectCreditsGlobals
> = z.object({
  accepts: shared.Accepts$outboundSchema.default(shared.Accepts.ApplicationXml),
  clientIdentifier: z.string().optional(),
  product: z.string().optional(),
  version: z.string().optional(),
  platform: z.string().optional(),
  platformVersion: z.string().optional(),
  device: z.string().optional(),
  model: z.string().optional(),
  deviceVendor: z.string().optional(),
  deviceName: z.string().optional(),
  marketplace: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    clientIdentifier: "Client-Identifier",
    product: "Product",
    version: "Version",
    platform: "Platform",
    platformVersion: "Platform-Version",
    device: "Device",
    model: "Model",
    deviceVendor: "Device-Vendor",
    deviceName: "Device-Name",
    marketplace: "Marketplace",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DetectCreditsGlobals$ {
  /** @deprecated use `DetectCreditsGlobals$inboundSchema` instead. */
  export const inboundSchema = DetectCreditsGlobals$inboundSchema;
  /** @deprecated use `DetectCreditsGlobals$outboundSchema` instead. */
  export const outboundSchema = DetectCreditsGlobals$outboundSchema;
  /** @deprecated use `DetectCreditsGlobals$Outbound` instead. */
  export type Outbound = DetectCreditsGlobals$Outbound;
}

export function detectCreditsGlobalsToJSON(
  detectCreditsGlobals: DetectCreditsGlobals,
): string {
  return JSON.stringify(
    DetectCreditsGlobals$outboundSchema.parse(detectCreditsGlobals),
  );
}

export function detectCreditsGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<DetectCreditsGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DetectCreditsGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DetectCreditsGlobals' from JSON`,
  );
}

/** @internal */
export const DetectCreditsRequest$inboundSchema: z.ZodType<
  DetectCreditsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  accepts: shared.Accepts$inboundSchema.default(shared.Accepts.ApplicationXml),
  "Client-Identifier": z.string().optional(),
  Product: z.string().optional(),
  Version: z.string().optional(),
  Platform: z.string().optional(),
  "Platform-Version": z.string().optional(),
  Device: z.string().optional(),
  Model: z.string().optional(),
  "Device-Vendor": z.string().optional(),
  "Device-Name": z.string().optional(),
  Marketplace: z.string().optional(),
  ids: z.string(),
  force: shared.BoolInt$inboundSchema.optional(),
  manual: shared.BoolInt$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "Client-Identifier": "clientIdentifier",
    "Product": "product",
    "Version": "version",
    "Platform": "platform",
    "Platform-Version": "platformVersion",
    "Device": "device",
    "Model": "model",
    "Device-Vendor": "deviceVendor",
    "Device-Name": "deviceName",
    "Marketplace": "marketplace",
  });
});

/** @internal */
export type DetectCreditsRequest$Outbound = {
  accepts: string;
  "Client-Identifier"?: string | undefined;
  Product?: string | undefined;
  Version?: string | undefined;
  Platform?: string | undefined;
  "Platform-Version"?: string | undefined;
  Device?: string | undefined;
  Model?: string | undefined;
  "Device-Vendor"?: string | undefined;
  "Device-Name"?: string | undefined;
  Marketplace?: string | undefined;
  ids: string;
  force?: number | undefined;
  manual?: number | undefined;
};

/** @internal */
export const DetectCreditsRequest$outboundSchema: z.ZodType<
  DetectCreditsRequest$Outbound,
  z.ZodTypeDef,
  DetectCreditsRequest
> = z.object({
  accepts: shared.Accepts$outboundSchema.default(shared.Accepts.ApplicationXml),
  clientIdentifier: z.string().optional(),
  product: z.string().optional(),
  version: z.string().optional(),
  platform: z.string().optional(),
  platformVersion: z.string().optional(),
  device: z.string().optional(),
  model: z.string().optional(),
  deviceVendor: z.string().optional(),
  deviceName: z.string().optional(),
  marketplace: z.string().optional(),
  ids: z.string(),
  force: shared.BoolInt$outboundSchema.optional(),
  manual: shared.BoolInt$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    clientIdentifier: "Client-Identifier",
    product: "Product",
    version: "Version",
    platform: "Platform",
    platformVersion: "Platform-Version",
    device: "Device",
    model: "Model",
    deviceVendor: "Device-Vendor",
    deviceName: "Device-Name",
    marketplace: "Marketplace",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DetectCreditsRequest$ {
  /** @deprecated use `DetectCreditsRequest$inboundSchema` instead. */
  export const inboundSchema = DetectCreditsRequest$inboundSchema;
  /** @deprecated use `DetectCreditsRequest$outboundSchema` instead. */
  export const outboundSchema = DetectCreditsRequest$outboundSchema;
  /** @deprecated use `DetectCreditsRequest$Outbound` instead. */
  export type Outbound = DetectCreditsRequest$Outbound;
}

export function detectCreditsRequestToJSON(
  detectCreditsRequest: DetectCreditsRequest,
): string {
  return JSON.stringify(
    DetectCreditsRequest$outboundSchema.parse(detectCreditsRequest),
  );
}

export function detectCreditsRequestFromJSON(
  jsonString: string,
): SafeParseResult<DetectCreditsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DetectCreditsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DetectCreditsRequest' from JSON`,
  );
}

/** @internal */
export const DetectCreditsResponse$inboundSchema: z.ZodType<
  DetectCreditsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
  });
});

/** @internal */
export type DetectCreditsResponse$Outbound = {
  ContentType: string;
  StatusCode: number;
  RawResponse: never;
};

/** @internal */
export const DetectCreditsResponse$outboundSchema: z.ZodType<
  DetectCreditsResponse$Outbound,
  z.ZodTypeDef,
  DetectCreditsResponse
> = z.object({
  contentType: z.string(),
  statusCode: z.number().int(),
  rawResponse: z.instanceof(Response).transform(() => {
    throw new Error("Response cannot be serialized");
  }),
}).transform((v) => {
  return remap$(v, {
    contentType: "ContentType",
    statusCode: "StatusCode",
    rawResponse: "RawResponse",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DetectCreditsResponse$ {
  /** @deprecated use `DetectCreditsResponse$inboundSchema` instead. */
  export const inboundSchema = DetectCreditsResponse$inboundSchema;
  /** @deprecated use `DetectCreditsResponse$outboundSchema` instead. */
  export const outboundSchema = DetectCreditsResponse$outboundSchema;
  /** @deprecated use `DetectCreditsResponse$Outbound` instead. */
  export type Outbound = DetectCreditsResponse$Outbound;
}

export function detectCreditsResponseToJSON(
  detectCreditsResponse: DetectCreditsResponse,
): string {
  return JSON.stringify(
    DetectCreditsResponse$outboundSchema.parse(detectCreditsResponse),
  );
}

export function detectCreditsResponseFromJSON(
  jsonString: string,
): SafeParseResult<DetectCreditsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DetectCreditsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DetectCreditsResponse' from JSON`,
  );
}
