/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetFoldersGlobals = {
  /**
   * An opaque identifier unique to the client
   */
  xPlexClientIdentifier?: string | undefined;
  /**
   * The name of the client product
   */
  xPlexProduct?: string | undefined;
  /**
   * The version of the client application
   */
  xPlexVersion?: string | undefined;
  /**
   * The platform of the client
   */
  xPlexPlatform?: string | undefined;
  /**
   * The version of the platform
   */
  xPlexPlatformVersion?: string | undefined;
  /**
   * A relatively friendly name for the client device
   */
  xPlexDevice?: string | undefined;
  /**
   * A potentially less friendly identifier for the device model
   */
  xPlexModel?: string | undefined;
  /**
   * The device vendor
   */
  xPlexDeviceVendor?: string | undefined;
  /**
   * A friendly name for the client
   */
  xPlexDeviceName?: string | undefined;
  /**
   * The marketplace on which the client application is distributed
   */
  xPlexMarketplace?: string | undefined;
};

export type GetFoldersRequest = {
  /**
   * An opaque identifier unique to the client
   */
  xPlexClientIdentifier?: string | undefined;
  /**
   * The name of the client product
   */
  xPlexProduct?: string | undefined;
  /**
   * The version of the client application
   */
  xPlexVersion?: string | undefined;
  /**
   * The platform of the client
   */
  xPlexPlatform?: string | undefined;
  /**
   * The version of the platform
   */
  xPlexPlatformVersion?: string | undefined;
  /**
   * A relatively friendly name for the client device
   */
  xPlexDevice?: string | undefined;
  /**
   * A potentially less friendly identifier for the device model
   */
  xPlexModel?: string | undefined;
  /**
   * The device vendor
   */
  xPlexDeviceVendor?: string | undefined;
  /**
   * A friendly name for the client
   */
  xPlexDeviceName?: string | undefined;
  /**
   * The marketplace on which the client application is distributed
   */
  xPlexMarketplace?: string | undefined;
  /**
   * Section identifier
   */
  sectionId: number;
};

export type GetFoldersDirectory = {
  fastKey?: string | undefined;
  key?: string | undefined;
  title?: string | undefined;
};

/**
 * `MediaContainer` is the root element of most Plex API responses. It serves as a generic container for various types of content (Metadata, Hubs, Directories, etc.) and includes pagination information (offset, size, totalSize) when applicable.
 *
 * @remarks
 * Common attributes: - identifier: Unique identifier for this container - size: Number of items in this response page - totalSize: Total number of items available (for pagination) - offset: Starting index of this page (for pagination)
 * The container often "hoists" common attributes from its children. For example, if all tracks in a container share the same album title, the `parentTitle` attribute may appear on the MediaContainer rather than being repeated on each track.
 */
export type GetFoldersMediaContainer = {
  identifier?: string | undefined;
  /**
   * The offset of where this container page starts among the total objects available. Also provided in the `X-Plex-Container-Start` header.
   *
   * @remarks
   */
  offset?: number | undefined;
  size?: number | undefined;
  /**
   * The total size of objects available. Also provided in the `X-Plex-Container-Total-Size` header.
   *
   * @remarks
   */
  totalSize?: number | undefined;
  directory?: Array<GetFoldersDirectory> | undefined;
};

/**
 * OK
 */
export type GetFoldersResponseBody = {
  mediaContainer?: GetFoldersMediaContainer | undefined;
};

export type GetFoldersResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * OK
   */
  object?: GetFoldersResponseBody | undefined;
};

/** @internal */
export const GetFoldersGlobals$inboundSchema: z.ZodType<
  GetFoldersGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  "X-Plex-Client-Identifier": z.string().optional(),
  "X-Plex-Product": z.string().optional(),
  "X-Plex-Version": z.string().optional(),
  "X-Plex-Platform": z.string().optional(),
  "X-Plex-Platform-Version": z.string().optional(),
  "X-Plex-Device": z.string().optional(),
  "X-Plex-Model": z.string().optional(),
  "X-Plex-Device-Vendor": z.string().optional(),
  "X-Plex-Device-Name": z.string().optional(),
  "X-Plex-Marketplace": z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "X-Plex-Client-Identifier": "xPlexClientIdentifier",
    "X-Plex-Product": "xPlexProduct",
    "X-Plex-Version": "xPlexVersion",
    "X-Plex-Platform": "xPlexPlatform",
    "X-Plex-Platform-Version": "xPlexPlatformVersion",
    "X-Plex-Device": "xPlexDevice",
    "X-Plex-Model": "xPlexModel",
    "X-Plex-Device-Vendor": "xPlexDeviceVendor",
    "X-Plex-Device-Name": "xPlexDeviceName",
    "X-Plex-Marketplace": "xPlexMarketplace",
  });
});

/** @internal */
export type GetFoldersGlobals$Outbound = {
  "X-Plex-Client-Identifier"?: string | undefined;
  "X-Plex-Product"?: string | undefined;
  "X-Plex-Version"?: string | undefined;
  "X-Plex-Platform"?: string | undefined;
  "X-Plex-Platform-Version"?: string | undefined;
  "X-Plex-Device"?: string | undefined;
  "X-Plex-Model"?: string | undefined;
  "X-Plex-Device-Vendor"?: string | undefined;
  "X-Plex-Device-Name"?: string | undefined;
  "X-Plex-Marketplace"?: string | undefined;
};

/** @internal */
export const GetFoldersGlobals$outboundSchema: z.ZodType<
  GetFoldersGlobals$Outbound,
  z.ZodTypeDef,
  GetFoldersGlobals
> = z.object({
  xPlexClientIdentifier: z.string().optional(),
  xPlexProduct: z.string().optional(),
  xPlexVersion: z.string().optional(),
  xPlexPlatform: z.string().optional(),
  xPlexPlatformVersion: z.string().optional(),
  xPlexDevice: z.string().optional(),
  xPlexModel: z.string().optional(),
  xPlexDeviceVendor: z.string().optional(),
  xPlexDeviceName: z.string().optional(),
  xPlexMarketplace: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    xPlexClientIdentifier: "X-Plex-Client-Identifier",
    xPlexProduct: "X-Plex-Product",
    xPlexVersion: "X-Plex-Version",
    xPlexPlatform: "X-Plex-Platform",
    xPlexPlatformVersion: "X-Plex-Platform-Version",
    xPlexDevice: "X-Plex-Device",
    xPlexModel: "X-Plex-Model",
    xPlexDeviceVendor: "X-Plex-Device-Vendor",
    xPlexDeviceName: "X-Plex-Device-Name",
    xPlexMarketplace: "X-Plex-Marketplace",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetFoldersGlobals$ {
  /** @deprecated use `GetFoldersGlobals$inboundSchema` instead. */
  export const inboundSchema = GetFoldersGlobals$inboundSchema;
  /** @deprecated use `GetFoldersGlobals$outboundSchema` instead. */
  export const outboundSchema = GetFoldersGlobals$outboundSchema;
  /** @deprecated use `GetFoldersGlobals$Outbound` instead. */
  export type Outbound = GetFoldersGlobals$Outbound;
}

export function getFoldersGlobalsToJSON(
  getFoldersGlobals: GetFoldersGlobals,
): string {
  return JSON.stringify(
    GetFoldersGlobals$outboundSchema.parse(getFoldersGlobals),
  );
}

export function getFoldersGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<GetFoldersGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetFoldersGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetFoldersGlobals' from JSON`,
  );
}

/** @internal */
export const GetFoldersRequest$inboundSchema: z.ZodType<
  GetFoldersRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  "X-Plex-Client-Identifier": z.string().optional(),
  "X-Plex-Product": z.string().optional(),
  "X-Plex-Version": z.string().optional(),
  "X-Plex-Platform": z.string().optional(),
  "X-Plex-Platform-Version": z.string().optional(),
  "X-Plex-Device": z.string().optional(),
  "X-Plex-Model": z.string().optional(),
  "X-Plex-Device-Vendor": z.string().optional(),
  "X-Plex-Device-Name": z.string().optional(),
  "X-Plex-Marketplace": z.string().optional(),
  sectionId: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "X-Plex-Client-Identifier": "xPlexClientIdentifier",
    "X-Plex-Product": "xPlexProduct",
    "X-Plex-Version": "xPlexVersion",
    "X-Plex-Platform": "xPlexPlatform",
    "X-Plex-Platform-Version": "xPlexPlatformVersion",
    "X-Plex-Device": "xPlexDevice",
    "X-Plex-Model": "xPlexModel",
    "X-Plex-Device-Vendor": "xPlexDeviceVendor",
    "X-Plex-Device-Name": "xPlexDeviceName",
    "X-Plex-Marketplace": "xPlexMarketplace",
  });
});

/** @internal */
export type GetFoldersRequest$Outbound = {
  "X-Plex-Client-Identifier"?: string | undefined;
  "X-Plex-Product"?: string | undefined;
  "X-Plex-Version"?: string | undefined;
  "X-Plex-Platform"?: string | undefined;
  "X-Plex-Platform-Version"?: string | undefined;
  "X-Plex-Device"?: string | undefined;
  "X-Plex-Model"?: string | undefined;
  "X-Plex-Device-Vendor"?: string | undefined;
  "X-Plex-Device-Name"?: string | undefined;
  "X-Plex-Marketplace"?: string | undefined;
  sectionId: number;
};

/** @internal */
export const GetFoldersRequest$outboundSchema: z.ZodType<
  GetFoldersRequest$Outbound,
  z.ZodTypeDef,
  GetFoldersRequest
> = z.object({
  xPlexClientIdentifier: z.string().optional(),
  xPlexProduct: z.string().optional(),
  xPlexVersion: z.string().optional(),
  xPlexPlatform: z.string().optional(),
  xPlexPlatformVersion: z.string().optional(),
  xPlexDevice: z.string().optional(),
  xPlexModel: z.string().optional(),
  xPlexDeviceVendor: z.string().optional(),
  xPlexDeviceName: z.string().optional(),
  xPlexMarketplace: z.string().optional(),
  sectionId: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    xPlexClientIdentifier: "X-Plex-Client-Identifier",
    xPlexProduct: "X-Plex-Product",
    xPlexVersion: "X-Plex-Version",
    xPlexPlatform: "X-Plex-Platform",
    xPlexPlatformVersion: "X-Plex-Platform-Version",
    xPlexDevice: "X-Plex-Device",
    xPlexModel: "X-Plex-Model",
    xPlexDeviceVendor: "X-Plex-Device-Vendor",
    xPlexDeviceName: "X-Plex-Device-Name",
    xPlexMarketplace: "X-Plex-Marketplace",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetFoldersRequest$ {
  /** @deprecated use `GetFoldersRequest$inboundSchema` instead. */
  export const inboundSchema = GetFoldersRequest$inboundSchema;
  /** @deprecated use `GetFoldersRequest$outboundSchema` instead. */
  export const outboundSchema = GetFoldersRequest$outboundSchema;
  /** @deprecated use `GetFoldersRequest$Outbound` instead. */
  export type Outbound = GetFoldersRequest$Outbound;
}

export function getFoldersRequestToJSON(
  getFoldersRequest: GetFoldersRequest,
): string {
  return JSON.stringify(
    GetFoldersRequest$outboundSchema.parse(getFoldersRequest),
  );
}

export function getFoldersRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetFoldersRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetFoldersRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetFoldersRequest' from JSON`,
  );
}

/** @internal */
export const GetFoldersDirectory$inboundSchema: z.ZodType<
  GetFoldersDirectory,
  z.ZodTypeDef,
  unknown
> = z.object({
  fastKey: z.string().optional(),
  key: z.string().optional(),
  title: z.string().optional(),
});

/** @internal */
export type GetFoldersDirectory$Outbound = {
  fastKey?: string | undefined;
  key?: string | undefined;
  title?: string | undefined;
};

/** @internal */
export const GetFoldersDirectory$outboundSchema: z.ZodType<
  GetFoldersDirectory$Outbound,
  z.ZodTypeDef,
  GetFoldersDirectory
> = z.object({
  fastKey: z.string().optional(),
  key: z.string().optional(),
  title: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetFoldersDirectory$ {
  /** @deprecated use `GetFoldersDirectory$inboundSchema` instead. */
  export const inboundSchema = GetFoldersDirectory$inboundSchema;
  /** @deprecated use `GetFoldersDirectory$outboundSchema` instead. */
  export const outboundSchema = GetFoldersDirectory$outboundSchema;
  /** @deprecated use `GetFoldersDirectory$Outbound` instead. */
  export type Outbound = GetFoldersDirectory$Outbound;
}

export function getFoldersDirectoryToJSON(
  getFoldersDirectory: GetFoldersDirectory,
): string {
  return JSON.stringify(
    GetFoldersDirectory$outboundSchema.parse(getFoldersDirectory),
  );
}

export function getFoldersDirectoryFromJSON(
  jsonString: string,
): SafeParseResult<GetFoldersDirectory, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetFoldersDirectory$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetFoldersDirectory' from JSON`,
  );
}

/** @internal */
export const GetFoldersMediaContainer$inboundSchema: z.ZodType<
  GetFoldersMediaContainer,
  z.ZodTypeDef,
  unknown
> = z.object({
  identifier: z.string().optional(),
  offset: z.number().int().optional(),
  size: z.number().int().optional(),
  totalSize: z.number().int().optional(),
  Directory: z.array(z.lazy(() => GetFoldersDirectory$inboundSchema))
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "Directory": "directory",
  });
});

/** @internal */
export type GetFoldersMediaContainer$Outbound = {
  identifier?: string | undefined;
  offset?: number | undefined;
  size?: number | undefined;
  totalSize?: number | undefined;
  Directory?: Array<GetFoldersDirectory$Outbound> | undefined;
};

/** @internal */
export const GetFoldersMediaContainer$outboundSchema: z.ZodType<
  GetFoldersMediaContainer$Outbound,
  z.ZodTypeDef,
  GetFoldersMediaContainer
> = z.object({
  identifier: z.string().optional(),
  offset: z.number().int().optional(),
  size: z.number().int().optional(),
  totalSize: z.number().int().optional(),
  directory: z.array(z.lazy(() => GetFoldersDirectory$outboundSchema))
    .optional(),
}).transform((v) => {
  return remap$(v, {
    directory: "Directory",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetFoldersMediaContainer$ {
  /** @deprecated use `GetFoldersMediaContainer$inboundSchema` instead. */
  export const inboundSchema = GetFoldersMediaContainer$inboundSchema;
  /** @deprecated use `GetFoldersMediaContainer$outboundSchema` instead. */
  export const outboundSchema = GetFoldersMediaContainer$outboundSchema;
  /** @deprecated use `GetFoldersMediaContainer$Outbound` instead. */
  export type Outbound = GetFoldersMediaContainer$Outbound;
}

export function getFoldersMediaContainerToJSON(
  getFoldersMediaContainer: GetFoldersMediaContainer,
): string {
  return JSON.stringify(
    GetFoldersMediaContainer$outboundSchema.parse(getFoldersMediaContainer),
  );
}

export function getFoldersMediaContainerFromJSON(
  jsonString: string,
): SafeParseResult<GetFoldersMediaContainer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetFoldersMediaContainer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetFoldersMediaContainer' from JSON`,
  );
}

/** @internal */
export const GetFoldersResponseBody$inboundSchema: z.ZodType<
  GetFoldersResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  MediaContainer: z.lazy(() => GetFoldersMediaContainer$inboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "MediaContainer": "mediaContainer",
  });
});

/** @internal */
export type GetFoldersResponseBody$Outbound = {
  MediaContainer?: GetFoldersMediaContainer$Outbound | undefined;
};

/** @internal */
export const GetFoldersResponseBody$outboundSchema: z.ZodType<
  GetFoldersResponseBody$Outbound,
  z.ZodTypeDef,
  GetFoldersResponseBody
> = z.object({
  mediaContainer: z.lazy(() => GetFoldersMediaContainer$outboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    mediaContainer: "MediaContainer",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetFoldersResponseBody$ {
  /** @deprecated use `GetFoldersResponseBody$inboundSchema` instead. */
  export const inboundSchema = GetFoldersResponseBody$inboundSchema;
  /** @deprecated use `GetFoldersResponseBody$outboundSchema` instead. */
  export const outboundSchema = GetFoldersResponseBody$outboundSchema;
  /** @deprecated use `GetFoldersResponseBody$Outbound` instead. */
  export type Outbound = GetFoldersResponseBody$Outbound;
}

export function getFoldersResponseBodyToJSON(
  getFoldersResponseBody: GetFoldersResponseBody,
): string {
  return JSON.stringify(
    GetFoldersResponseBody$outboundSchema.parse(getFoldersResponseBody),
  );
}

export function getFoldersResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetFoldersResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetFoldersResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetFoldersResponseBody' from JSON`,
  );
}

/** @internal */
export const GetFoldersResponse$inboundSchema: z.ZodType<
  GetFoldersResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
  object: z.lazy(() => GetFoldersResponseBody$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
  });
});

/** @internal */
export type GetFoldersResponse$Outbound = {
  ContentType: string;
  StatusCode: number;
  RawResponse: never;
  object?: GetFoldersResponseBody$Outbound | undefined;
};

/** @internal */
export const GetFoldersResponse$outboundSchema: z.ZodType<
  GetFoldersResponse$Outbound,
  z.ZodTypeDef,
  GetFoldersResponse
> = z.object({
  contentType: z.string(),
  statusCode: z.number().int(),
  rawResponse: z.instanceof(Response).transform(() => {
    throw new Error("Response cannot be serialized");
  }),
  object: z.lazy(() => GetFoldersResponseBody$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    contentType: "ContentType",
    statusCode: "StatusCode",
    rawResponse: "RawResponse",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetFoldersResponse$ {
  /** @deprecated use `GetFoldersResponse$inboundSchema` instead. */
  export const inboundSchema = GetFoldersResponse$inboundSchema;
  /** @deprecated use `GetFoldersResponse$outboundSchema` instead. */
  export const outboundSchema = GetFoldersResponse$outboundSchema;
  /** @deprecated use `GetFoldersResponse$Outbound` instead. */
  export type Outbound = GetFoldersResponse$Outbound;
}

export function getFoldersResponseToJSON(
  getFoldersResponse: GetFoldersResponse,
): string {
  return JSON.stringify(
    GetFoldersResponse$outboundSchema.parse(getFoldersResponse),
  );
}

export function getFoldersResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetFoldersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetFoldersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetFoldersResponse' from JSON`,
  );
}
