/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type GetItemArtworkGlobals = {
  /**
   * Indicates the client accepts the indicated media types
   */
  accepts?: shared.Accepts | undefined;
  /**
   * An opaque identifier unique to the client
   */
  clientIdentifier?: string | undefined;
  /**
   * The name of the client product
   */
  product?: string | undefined;
  /**
   * The version of the client application
   */
  version?: string | undefined;
  /**
   * The platform of the client
   */
  platform?: string | undefined;
  /**
   * The version of the platform
   */
  platformVersion?: string | undefined;
  /**
   * A relatively friendly name for the client device
   */
  device?: string | undefined;
  /**
   * A potentially less friendly identifier for the device model
   */
  model?: string | undefined;
  /**
   * The device vendor
   */
  deviceVendor?: string | undefined;
  /**
   * A friendly name for the client
   */
  deviceName?: string | undefined;
  /**
   * The marketplace on which the client application is distributed
   */
  marketplace?: string | undefined;
};

export enum GetItemArtworkElement {
  Thumb = "thumb",
  Art = "art",
  ClearLogo = "clearLogo",
  Banner = "banner",
  Poster = "poster",
  Theme = "theme",
}

export type GetItemArtworkRequest = {
  /**
   * Indicates the client accepts the indicated media types
   */
  accepts?: shared.Accepts | undefined;
  /**
   * An opaque identifier unique to the client
   */
  clientIdentifier?: string | undefined;
  /**
   * The name of the client product
   */
  product?: string | undefined;
  /**
   * The version of the client application
   */
  version?: string | undefined;
  /**
   * The platform of the client
   */
  platform?: string | undefined;
  /**
   * The version of the platform
   */
  platformVersion?: string | undefined;
  /**
   * A relatively friendly name for the client device
   */
  device?: string | undefined;
  /**
   * A potentially less friendly identifier for the device model
   */
  model?: string | undefined;
  /**
   * The device vendor
   */
  deviceVendor?: string | undefined;
  /**
   * A friendly name for the client
   */
  deviceName?: string | undefined;
  /**
   * The marketplace on which the client application is distributed
   */
  marketplace?: string | undefined;
  ids: string;
  element: GetItemArtworkElement;
  /**
   * A timestamp on the element used for cache management in the client
   */
  timestamp: number;
};

export type GetItemArtworkResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * OK
   */
  twoHundredAudioMpeg3ResponseStream?: ReadableStream<Uint8Array> | undefined;
  /**
   * OK
   */
  twoHundredImageJpegResponseStream?: ReadableStream<Uint8Array> | undefined;
};

/** @internal */
export const GetItemArtworkGlobals$inboundSchema: z.ZodType<
  GetItemArtworkGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  accepts: shared.Accepts$inboundSchema.default(shared.Accepts.ApplicationXml),
  "Client-Identifier": z.string().optional(),
  Product: z.string().optional(),
  Version: z.string().optional(),
  Platform: z.string().optional(),
  "Platform-Version": z.string().optional(),
  Device: z.string().optional(),
  Model: z.string().optional(),
  "Device-Vendor": z.string().optional(),
  "Device-Name": z.string().optional(),
  Marketplace: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "Client-Identifier": "clientIdentifier",
    "Product": "product",
    "Version": "version",
    "Platform": "platform",
    "Platform-Version": "platformVersion",
    "Device": "device",
    "Model": "model",
    "Device-Vendor": "deviceVendor",
    "Device-Name": "deviceName",
    "Marketplace": "marketplace",
  });
});

/** @internal */
export type GetItemArtworkGlobals$Outbound = {
  accepts: string;
  "Client-Identifier"?: string | undefined;
  Product?: string | undefined;
  Version?: string | undefined;
  Platform?: string | undefined;
  "Platform-Version"?: string | undefined;
  Device?: string | undefined;
  Model?: string | undefined;
  "Device-Vendor"?: string | undefined;
  "Device-Name"?: string | undefined;
  Marketplace?: string | undefined;
};

/** @internal */
export const GetItemArtworkGlobals$outboundSchema: z.ZodType<
  GetItemArtworkGlobals$Outbound,
  z.ZodTypeDef,
  GetItemArtworkGlobals
> = z.object({
  accepts: shared.Accepts$outboundSchema.default(shared.Accepts.ApplicationXml),
  clientIdentifier: z.string().optional(),
  product: z.string().optional(),
  version: z.string().optional(),
  platform: z.string().optional(),
  platformVersion: z.string().optional(),
  device: z.string().optional(),
  model: z.string().optional(),
  deviceVendor: z.string().optional(),
  deviceName: z.string().optional(),
  marketplace: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    clientIdentifier: "Client-Identifier",
    product: "Product",
    version: "Version",
    platform: "Platform",
    platformVersion: "Platform-Version",
    device: "Device",
    model: "Model",
    deviceVendor: "Device-Vendor",
    deviceName: "Device-Name",
    marketplace: "Marketplace",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetItemArtworkGlobals$ {
  /** @deprecated use `GetItemArtworkGlobals$inboundSchema` instead. */
  export const inboundSchema = GetItemArtworkGlobals$inboundSchema;
  /** @deprecated use `GetItemArtworkGlobals$outboundSchema` instead. */
  export const outboundSchema = GetItemArtworkGlobals$outboundSchema;
  /** @deprecated use `GetItemArtworkGlobals$Outbound` instead. */
  export type Outbound = GetItemArtworkGlobals$Outbound;
}

export function getItemArtworkGlobalsToJSON(
  getItemArtworkGlobals: GetItemArtworkGlobals,
): string {
  return JSON.stringify(
    GetItemArtworkGlobals$outboundSchema.parse(getItemArtworkGlobals),
  );
}

export function getItemArtworkGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<GetItemArtworkGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetItemArtworkGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetItemArtworkGlobals' from JSON`,
  );
}

/** @internal */
export const GetItemArtworkElement$inboundSchema: z.ZodNativeEnum<
  typeof GetItemArtworkElement
> = z.nativeEnum(GetItemArtworkElement);

/** @internal */
export const GetItemArtworkElement$outboundSchema: z.ZodNativeEnum<
  typeof GetItemArtworkElement
> = GetItemArtworkElement$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetItemArtworkElement$ {
  /** @deprecated use `GetItemArtworkElement$inboundSchema` instead. */
  export const inboundSchema = GetItemArtworkElement$inboundSchema;
  /** @deprecated use `GetItemArtworkElement$outboundSchema` instead. */
  export const outboundSchema = GetItemArtworkElement$outboundSchema;
}

/** @internal */
export const GetItemArtworkRequest$inboundSchema: z.ZodType<
  GetItemArtworkRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  accepts: shared.Accepts$inboundSchema.default(shared.Accepts.ApplicationXml),
  "Client-Identifier": z.string().optional(),
  Product: z.string().optional(),
  Version: z.string().optional(),
  Platform: z.string().optional(),
  "Platform-Version": z.string().optional(),
  Device: z.string().optional(),
  Model: z.string().optional(),
  "Device-Vendor": z.string().optional(),
  "Device-Name": z.string().optional(),
  Marketplace: z.string().optional(),
  ids: z.string(),
  element: GetItemArtworkElement$inboundSchema,
  timestamp: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "Client-Identifier": "clientIdentifier",
    "Product": "product",
    "Version": "version",
    "Platform": "platform",
    "Platform-Version": "platformVersion",
    "Device": "device",
    "Model": "model",
    "Device-Vendor": "deviceVendor",
    "Device-Name": "deviceName",
    "Marketplace": "marketplace",
  });
});

/** @internal */
export type GetItemArtworkRequest$Outbound = {
  accepts: string;
  "Client-Identifier"?: string | undefined;
  Product?: string | undefined;
  Version?: string | undefined;
  Platform?: string | undefined;
  "Platform-Version"?: string | undefined;
  Device?: string | undefined;
  Model?: string | undefined;
  "Device-Vendor"?: string | undefined;
  "Device-Name"?: string | undefined;
  Marketplace?: string | undefined;
  ids: string;
  element: string;
  timestamp: number;
};

/** @internal */
export const GetItemArtworkRequest$outboundSchema: z.ZodType<
  GetItemArtworkRequest$Outbound,
  z.ZodTypeDef,
  GetItemArtworkRequest
> = z.object({
  accepts: shared.Accepts$outboundSchema.default(shared.Accepts.ApplicationXml),
  clientIdentifier: z.string().optional(),
  product: z.string().optional(),
  version: z.string().optional(),
  platform: z.string().optional(),
  platformVersion: z.string().optional(),
  device: z.string().optional(),
  model: z.string().optional(),
  deviceVendor: z.string().optional(),
  deviceName: z.string().optional(),
  marketplace: z.string().optional(),
  ids: z.string(),
  element: GetItemArtworkElement$outboundSchema,
  timestamp: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    clientIdentifier: "Client-Identifier",
    product: "Product",
    version: "Version",
    platform: "Platform",
    platformVersion: "Platform-Version",
    device: "Device",
    model: "Model",
    deviceVendor: "Device-Vendor",
    deviceName: "Device-Name",
    marketplace: "Marketplace",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetItemArtworkRequest$ {
  /** @deprecated use `GetItemArtworkRequest$inboundSchema` instead. */
  export const inboundSchema = GetItemArtworkRequest$inboundSchema;
  /** @deprecated use `GetItemArtworkRequest$outboundSchema` instead. */
  export const outboundSchema = GetItemArtworkRequest$outboundSchema;
  /** @deprecated use `GetItemArtworkRequest$Outbound` instead. */
  export type Outbound = GetItemArtworkRequest$Outbound;
}

export function getItemArtworkRequestToJSON(
  getItemArtworkRequest: GetItemArtworkRequest,
): string {
  return JSON.stringify(
    GetItemArtworkRequest$outboundSchema.parse(getItemArtworkRequest),
  );
}

export function getItemArtworkRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetItemArtworkRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetItemArtworkRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetItemArtworkRequest' from JSON`,
  );
}

/** @internal */
export const GetItemArtworkResponse$inboundSchema: z.ZodType<
  GetItemArtworkResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
  "200_audio/mpeg3_response-stream": z.instanceof(ReadableStream<Uint8Array>)
    .optional(),
  "200_image/jpeg_response-stream": z.instanceof(ReadableStream<Uint8Array>)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
    "200_audio/mpeg3_response-stream": "twoHundredAudioMpeg3ResponseStream",
    "200_image/jpeg_response-stream": "twoHundredImageJpegResponseStream",
  });
});

/** @internal */
export type GetItemArtworkResponse$Outbound = {
  ContentType: string;
  StatusCode: number;
  RawResponse: never;
  "200_audio/mpeg3_response-stream"?: ReadableStream<Uint8Array> | undefined;
  "200_image/jpeg_response-stream"?: ReadableStream<Uint8Array> | undefined;
};

/** @internal */
export const GetItemArtworkResponse$outboundSchema: z.ZodType<
  GetItemArtworkResponse$Outbound,
  z.ZodTypeDef,
  GetItemArtworkResponse
> = z.object({
  contentType: z.string(),
  statusCode: z.number().int(),
  rawResponse: z.instanceof(Response).transform(() => {
    throw new Error("Response cannot be serialized");
  }),
  twoHundredAudioMpeg3ResponseStream: z.instanceof(ReadableStream<Uint8Array>)
    .optional(),
  twoHundredImageJpegResponseStream: z.instanceof(ReadableStream<Uint8Array>)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    contentType: "ContentType",
    statusCode: "StatusCode",
    rawResponse: "RawResponse",
    twoHundredAudioMpeg3ResponseStream: "200_audio/mpeg3_response-stream",
    twoHundredImageJpegResponseStream: "200_image/jpeg_response-stream",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetItemArtworkResponse$ {
  /** @deprecated use `GetItemArtworkResponse$inboundSchema` instead. */
  export const inboundSchema = GetItemArtworkResponse$inboundSchema;
  /** @deprecated use `GetItemArtworkResponse$outboundSchema` instead. */
  export const outboundSchema = GetItemArtworkResponse$outboundSchema;
  /** @deprecated use `GetItemArtworkResponse$Outbound` instead. */
  export type Outbound = GetItemArtworkResponse$Outbound;
}

export function getItemArtworkResponseToJSON(
  getItemArtworkResponse: GetItemArtworkResponse,
): string {
  return JSON.stringify(
    GetItemArtworkResponse$outboundSchema.parse(getItemArtworkResponse),
  );
}

export function getItemArtworkResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetItemArtworkResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetItemArtworkResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetItemArtworkResponse' from JSON`,
  );
}
