/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetIdentityMediaContainer = {
  /**
   * Indicates whether this server has been claimed by a user
   */
  claimed?: boolean | undefined;
  /**
   * A unique identifier of the computer
   */
  machineIdentifier?: string | undefined;
  size?: number | undefined;
  /**
   * The full version string of the PMS
   */
  version?: string | undefined;
};

/**
 * OK
 */
export type GetIdentityResponseBody = {
  mediaContainer?: GetIdentityMediaContainer | undefined;
};

export type GetIdentityResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * OK
   */
  object?: GetIdentityResponseBody | undefined;
};

/** @internal */
export const GetIdentityMediaContainer$inboundSchema: z.ZodType<
  GetIdentityMediaContainer,
  z.ZodTypeDef,
  unknown
> = z.object({
  claimed: z.boolean().optional(),
  machineIdentifier: z.string().optional(),
  size: z.number().int().optional(),
  version: z.string().optional(),
});

/** @internal */
export type GetIdentityMediaContainer$Outbound = {
  claimed?: boolean | undefined;
  machineIdentifier?: string | undefined;
  size?: number | undefined;
  version?: string | undefined;
};

/** @internal */
export const GetIdentityMediaContainer$outboundSchema: z.ZodType<
  GetIdentityMediaContainer$Outbound,
  z.ZodTypeDef,
  GetIdentityMediaContainer
> = z.object({
  claimed: z.boolean().optional(),
  machineIdentifier: z.string().optional(),
  size: z.number().int().optional(),
  version: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetIdentityMediaContainer$ {
  /** @deprecated use `GetIdentityMediaContainer$inboundSchema` instead. */
  export const inboundSchema = GetIdentityMediaContainer$inboundSchema;
  /** @deprecated use `GetIdentityMediaContainer$outboundSchema` instead. */
  export const outboundSchema = GetIdentityMediaContainer$outboundSchema;
  /** @deprecated use `GetIdentityMediaContainer$Outbound` instead. */
  export type Outbound = GetIdentityMediaContainer$Outbound;
}

export function getIdentityMediaContainerToJSON(
  getIdentityMediaContainer: GetIdentityMediaContainer,
): string {
  return JSON.stringify(
    GetIdentityMediaContainer$outboundSchema.parse(getIdentityMediaContainer),
  );
}

export function getIdentityMediaContainerFromJSON(
  jsonString: string,
): SafeParseResult<GetIdentityMediaContainer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetIdentityMediaContainer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetIdentityMediaContainer' from JSON`,
  );
}

/** @internal */
export const GetIdentityResponseBody$inboundSchema: z.ZodType<
  GetIdentityResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  MediaContainer: z.lazy(() => GetIdentityMediaContainer$inboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "MediaContainer": "mediaContainer",
  });
});

/** @internal */
export type GetIdentityResponseBody$Outbound = {
  MediaContainer?: GetIdentityMediaContainer$Outbound | undefined;
};

/** @internal */
export const GetIdentityResponseBody$outboundSchema: z.ZodType<
  GetIdentityResponseBody$Outbound,
  z.ZodTypeDef,
  GetIdentityResponseBody
> = z.object({
  mediaContainer: z.lazy(() => GetIdentityMediaContainer$outboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    mediaContainer: "MediaContainer",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetIdentityResponseBody$ {
  /** @deprecated use `GetIdentityResponseBody$inboundSchema` instead. */
  export const inboundSchema = GetIdentityResponseBody$inboundSchema;
  /** @deprecated use `GetIdentityResponseBody$outboundSchema` instead. */
  export const outboundSchema = GetIdentityResponseBody$outboundSchema;
  /** @deprecated use `GetIdentityResponseBody$Outbound` instead. */
  export type Outbound = GetIdentityResponseBody$Outbound;
}

export function getIdentityResponseBodyToJSON(
  getIdentityResponseBody: GetIdentityResponseBody,
): string {
  return JSON.stringify(
    GetIdentityResponseBody$outboundSchema.parse(getIdentityResponseBody),
  );
}

export function getIdentityResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetIdentityResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetIdentityResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetIdentityResponseBody' from JSON`,
  );
}

/** @internal */
export const GetIdentityResponse$inboundSchema: z.ZodType<
  GetIdentityResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
  object: z.lazy(() => GetIdentityResponseBody$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
  });
});

/** @internal */
export type GetIdentityResponse$Outbound = {
  ContentType: string;
  StatusCode: number;
  RawResponse: never;
  object?: GetIdentityResponseBody$Outbound | undefined;
};

/** @internal */
export const GetIdentityResponse$outboundSchema: z.ZodType<
  GetIdentityResponse$Outbound,
  z.ZodTypeDef,
  GetIdentityResponse
> = z.object({
  contentType: z.string(),
  statusCode: z.number().int(),
  rawResponse: z.instanceof(Response).transform(() => {
    throw new Error("Response cannot be serialized");
  }),
  object: z.lazy(() => GetIdentityResponseBody$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    contentType: "ContentType",
    statusCode: "StatusCode",
    rawResponse: "RawResponse",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetIdentityResponse$ {
  /** @deprecated use `GetIdentityResponse$inboundSchema` instead. */
  export const inboundSchema = GetIdentityResponse$inboundSchema;
  /** @deprecated use `GetIdentityResponse$outboundSchema` instead. */
  export const outboundSchema = GetIdentityResponse$outboundSchema;
  /** @deprecated use `GetIdentityResponse$Outbound` instead. */
  export type Outbound = GetIdentityResponse$Outbound;
}

export function getIdentityResponseToJSON(
  getIdentityResponse: GetIdentityResponse,
): string {
  return JSON.stringify(
    GetIdentityResponse$outboundSchema.parse(getIdentityResponse),
  );
}

export function getIdentityResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetIdentityResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetIdentityResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetIdentityResponse' from JSON`,
  );
}
