/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetPlaylistGeneratorsGlobals = {
  /**
   * An opaque identifier unique to the client
   */
  xPlexClientIdentifier?: string | undefined;
  /**
   * The name of the client product
   */
  xPlexProduct?: string | undefined;
  /**
   * The version of the client application
   */
  xPlexVersion?: string | undefined;
  /**
   * The platform of the client
   */
  xPlexPlatform?: string | undefined;
  /**
   * The version of the platform
   */
  xPlexPlatformVersion?: string | undefined;
  /**
   * A relatively friendly name for the client device
   */
  xPlexDevice?: string | undefined;
  /**
   * A potentially less friendly identifier for the device model
   */
  xPlexModel?: string | undefined;
  /**
   * The device vendor
   */
  xPlexDeviceVendor?: string | undefined;
  /**
   * A friendly name for the client
   */
  xPlexDeviceName?: string | undefined;
  /**
   * The marketplace on which the client application is distributed
   */
  xPlexMarketplace?: string | undefined;
};

export type GetPlaylistGeneratorsRequest = {
  /**
   * An opaque identifier unique to the client
   */
  xPlexClientIdentifier?: string | undefined;
  /**
   * The name of the client product
   */
  xPlexProduct?: string | undefined;
  /**
   * The version of the client application
   */
  xPlexVersion?: string | undefined;
  /**
   * The platform of the client
   */
  xPlexPlatform?: string | undefined;
  /**
   * The version of the platform
   */
  xPlexPlatformVersion?: string | undefined;
  /**
   * A relatively friendly name for the client device
   */
  xPlexDevice?: string | undefined;
  /**
   * A potentially less friendly identifier for the device model
   */
  xPlexModel?: string | undefined;
  /**
   * The device vendor
   */
  xPlexDeviceVendor?: string | undefined;
  /**
   * A friendly name for the client
   */
  xPlexDeviceName?: string | undefined;
  /**
   * The marketplace on which the client application is distributed
   */
  xPlexMarketplace?: string | undefined;
  /**
   * The ID of the playlist
   */
  playlistId: number;
};

/**
 * The type of playlist generator.
 *
 * @remarks
 *
 *   - -1: A smart playlist generator
 *   - 42: A optimized version generator
 */
export enum GetPlaylistGeneratorsType {
  Minus1 = -1,
  FortyTwo = 42,
}

export type PlayQueueGenerator = {
  changedAt?: number | undefined;
  createdAt?: number | undefined;
  id?: number | undefined;
  playlistID?: number | undefined;
  /**
   * The type of playlist generator.
   *
   * @remarks
   *
   *   - -1: A smart playlist generator
   *   - 42: A optimized version generator
   */
  type?: GetPlaylistGeneratorsType | undefined;
  updatedAt?: number | undefined;
  /**
   * The URI indicating the search for this generator
   */
  uri?: string | undefined;
};

/**
 * `MediaContainer` is the root element of most Plex API responses. It serves as a generic container for various types of content (Metadata, Hubs, Directories, etc.) and includes pagination information (offset, size, totalSize) when applicable.
 *
 * @remarks
 * Common attributes: - identifier: Unique identifier for this container - size: Number of items in this response page - totalSize: Total number of items available (for pagination) - offset: Starting index of this page (for pagination)
 * The container often "hoists" common attributes from its children. For example, if all tracks in a container share the same album title, the `parentTitle` attribute may appear on the MediaContainer rather than being repeated on each track.
 */
export type GetPlaylistGeneratorsMediaContainer = {
  identifier?: string | undefined;
  /**
   * The offset of where this container page starts among the total objects available. Also provided in the `X-Plex-Container-Start` header.
   *
   * @remarks
   */
  offset?: number | undefined;
  size?: number | undefined;
  /**
   * The total size of objects available. Also provided in the `X-Plex-Container-Total-Size` header.
   *
   * @remarks
   */
  totalSize?: number | undefined;
  playQueueGenerator?: Array<PlayQueueGenerator> | undefined;
};

/**
 * OK
 */
export type GetPlaylistGeneratorsResponseBody = {
  mediaContainer?: GetPlaylistGeneratorsMediaContainer | undefined;
};

export type GetPlaylistGeneratorsResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * OK
   */
  object?: GetPlaylistGeneratorsResponseBody | undefined;
};

/** @internal */
export const GetPlaylistGeneratorsGlobals$inboundSchema: z.ZodType<
  GetPlaylistGeneratorsGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  "X-Plex-Client-Identifier": z.string().optional(),
  "X-Plex-Product": z.string().optional(),
  "X-Plex-Version": z.string().optional(),
  "X-Plex-Platform": z.string().optional(),
  "X-Plex-Platform-Version": z.string().optional(),
  "X-Plex-Device": z.string().optional(),
  "X-Plex-Model": z.string().optional(),
  "X-Plex-Device-Vendor": z.string().optional(),
  "X-Plex-Device-Name": z.string().optional(),
  "X-Plex-Marketplace": z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "X-Plex-Client-Identifier": "xPlexClientIdentifier",
    "X-Plex-Product": "xPlexProduct",
    "X-Plex-Version": "xPlexVersion",
    "X-Plex-Platform": "xPlexPlatform",
    "X-Plex-Platform-Version": "xPlexPlatformVersion",
    "X-Plex-Device": "xPlexDevice",
    "X-Plex-Model": "xPlexModel",
    "X-Plex-Device-Vendor": "xPlexDeviceVendor",
    "X-Plex-Device-Name": "xPlexDeviceName",
    "X-Plex-Marketplace": "xPlexMarketplace",
  });
});

/** @internal */
export type GetPlaylistGeneratorsGlobals$Outbound = {
  "X-Plex-Client-Identifier"?: string | undefined;
  "X-Plex-Product"?: string | undefined;
  "X-Plex-Version"?: string | undefined;
  "X-Plex-Platform"?: string | undefined;
  "X-Plex-Platform-Version"?: string | undefined;
  "X-Plex-Device"?: string | undefined;
  "X-Plex-Model"?: string | undefined;
  "X-Plex-Device-Vendor"?: string | undefined;
  "X-Plex-Device-Name"?: string | undefined;
  "X-Plex-Marketplace"?: string | undefined;
};

/** @internal */
export const GetPlaylistGeneratorsGlobals$outboundSchema: z.ZodType<
  GetPlaylistGeneratorsGlobals$Outbound,
  z.ZodTypeDef,
  GetPlaylistGeneratorsGlobals
> = z.object({
  xPlexClientIdentifier: z.string().optional(),
  xPlexProduct: z.string().optional(),
  xPlexVersion: z.string().optional(),
  xPlexPlatform: z.string().optional(),
  xPlexPlatformVersion: z.string().optional(),
  xPlexDevice: z.string().optional(),
  xPlexModel: z.string().optional(),
  xPlexDeviceVendor: z.string().optional(),
  xPlexDeviceName: z.string().optional(),
  xPlexMarketplace: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    xPlexClientIdentifier: "X-Plex-Client-Identifier",
    xPlexProduct: "X-Plex-Product",
    xPlexVersion: "X-Plex-Version",
    xPlexPlatform: "X-Plex-Platform",
    xPlexPlatformVersion: "X-Plex-Platform-Version",
    xPlexDevice: "X-Plex-Device",
    xPlexModel: "X-Plex-Model",
    xPlexDeviceVendor: "X-Plex-Device-Vendor",
    xPlexDeviceName: "X-Plex-Device-Name",
    xPlexMarketplace: "X-Plex-Marketplace",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetPlaylistGeneratorsGlobals$ {
  /** @deprecated use `GetPlaylistGeneratorsGlobals$inboundSchema` instead. */
  export const inboundSchema = GetPlaylistGeneratorsGlobals$inboundSchema;
  /** @deprecated use `GetPlaylistGeneratorsGlobals$outboundSchema` instead. */
  export const outboundSchema = GetPlaylistGeneratorsGlobals$outboundSchema;
  /** @deprecated use `GetPlaylistGeneratorsGlobals$Outbound` instead. */
  export type Outbound = GetPlaylistGeneratorsGlobals$Outbound;
}

export function getPlaylistGeneratorsGlobalsToJSON(
  getPlaylistGeneratorsGlobals: GetPlaylistGeneratorsGlobals,
): string {
  return JSON.stringify(
    GetPlaylistGeneratorsGlobals$outboundSchema.parse(
      getPlaylistGeneratorsGlobals,
    ),
  );
}

export function getPlaylistGeneratorsGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<GetPlaylistGeneratorsGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPlaylistGeneratorsGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlaylistGeneratorsGlobals' from JSON`,
  );
}

/** @internal */
export const GetPlaylistGeneratorsRequest$inboundSchema: z.ZodType<
  GetPlaylistGeneratorsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  "X-Plex-Client-Identifier": z.string().optional(),
  "X-Plex-Product": z.string().optional(),
  "X-Plex-Version": z.string().optional(),
  "X-Plex-Platform": z.string().optional(),
  "X-Plex-Platform-Version": z.string().optional(),
  "X-Plex-Device": z.string().optional(),
  "X-Plex-Model": z.string().optional(),
  "X-Plex-Device-Vendor": z.string().optional(),
  "X-Plex-Device-Name": z.string().optional(),
  "X-Plex-Marketplace": z.string().optional(),
  playlistId: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "X-Plex-Client-Identifier": "xPlexClientIdentifier",
    "X-Plex-Product": "xPlexProduct",
    "X-Plex-Version": "xPlexVersion",
    "X-Plex-Platform": "xPlexPlatform",
    "X-Plex-Platform-Version": "xPlexPlatformVersion",
    "X-Plex-Device": "xPlexDevice",
    "X-Plex-Model": "xPlexModel",
    "X-Plex-Device-Vendor": "xPlexDeviceVendor",
    "X-Plex-Device-Name": "xPlexDeviceName",
    "X-Plex-Marketplace": "xPlexMarketplace",
  });
});

/** @internal */
export type GetPlaylistGeneratorsRequest$Outbound = {
  "X-Plex-Client-Identifier"?: string | undefined;
  "X-Plex-Product"?: string | undefined;
  "X-Plex-Version"?: string | undefined;
  "X-Plex-Platform"?: string | undefined;
  "X-Plex-Platform-Version"?: string | undefined;
  "X-Plex-Device"?: string | undefined;
  "X-Plex-Model"?: string | undefined;
  "X-Plex-Device-Vendor"?: string | undefined;
  "X-Plex-Device-Name"?: string | undefined;
  "X-Plex-Marketplace"?: string | undefined;
  playlistId: number;
};

/** @internal */
export const GetPlaylistGeneratorsRequest$outboundSchema: z.ZodType<
  GetPlaylistGeneratorsRequest$Outbound,
  z.ZodTypeDef,
  GetPlaylistGeneratorsRequest
> = z.object({
  xPlexClientIdentifier: z.string().optional(),
  xPlexProduct: z.string().optional(),
  xPlexVersion: z.string().optional(),
  xPlexPlatform: z.string().optional(),
  xPlexPlatformVersion: z.string().optional(),
  xPlexDevice: z.string().optional(),
  xPlexModel: z.string().optional(),
  xPlexDeviceVendor: z.string().optional(),
  xPlexDeviceName: z.string().optional(),
  xPlexMarketplace: z.string().optional(),
  playlistId: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    xPlexClientIdentifier: "X-Plex-Client-Identifier",
    xPlexProduct: "X-Plex-Product",
    xPlexVersion: "X-Plex-Version",
    xPlexPlatform: "X-Plex-Platform",
    xPlexPlatformVersion: "X-Plex-Platform-Version",
    xPlexDevice: "X-Plex-Device",
    xPlexModel: "X-Plex-Model",
    xPlexDeviceVendor: "X-Plex-Device-Vendor",
    xPlexDeviceName: "X-Plex-Device-Name",
    xPlexMarketplace: "X-Plex-Marketplace",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetPlaylistGeneratorsRequest$ {
  /** @deprecated use `GetPlaylistGeneratorsRequest$inboundSchema` instead. */
  export const inboundSchema = GetPlaylistGeneratorsRequest$inboundSchema;
  /** @deprecated use `GetPlaylistGeneratorsRequest$outboundSchema` instead. */
  export const outboundSchema = GetPlaylistGeneratorsRequest$outboundSchema;
  /** @deprecated use `GetPlaylistGeneratorsRequest$Outbound` instead. */
  export type Outbound = GetPlaylistGeneratorsRequest$Outbound;
}

export function getPlaylistGeneratorsRequestToJSON(
  getPlaylistGeneratorsRequest: GetPlaylistGeneratorsRequest,
): string {
  return JSON.stringify(
    GetPlaylistGeneratorsRequest$outboundSchema.parse(
      getPlaylistGeneratorsRequest,
    ),
  );
}

export function getPlaylistGeneratorsRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetPlaylistGeneratorsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPlaylistGeneratorsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlaylistGeneratorsRequest' from JSON`,
  );
}

/** @internal */
export const GetPlaylistGeneratorsType$inboundSchema: z.ZodNativeEnum<
  typeof GetPlaylistGeneratorsType
> = z.nativeEnum(GetPlaylistGeneratorsType);

/** @internal */
export const GetPlaylistGeneratorsType$outboundSchema: z.ZodNativeEnum<
  typeof GetPlaylistGeneratorsType
> = GetPlaylistGeneratorsType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetPlaylistGeneratorsType$ {
  /** @deprecated use `GetPlaylistGeneratorsType$inboundSchema` instead. */
  export const inboundSchema = GetPlaylistGeneratorsType$inboundSchema;
  /** @deprecated use `GetPlaylistGeneratorsType$outboundSchema` instead. */
  export const outboundSchema = GetPlaylistGeneratorsType$outboundSchema;
}

/** @internal */
export const PlayQueueGenerator$inboundSchema: z.ZodType<
  PlayQueueGenerator,
  z.ZodTypeDef,
  unknown
> = z.object({
  changedAt: z.number().int().optional(),
  createdAt: z.number().int().optional(),
  id: z.number().int().optional(),
  playlistID: z.number().int().optional(),
  type: GetPlaylistGeneratorsType$inboundSchema.optional(),
  updatedAt: z.number().int().optional(),
  uri: z.string().optional(),
});

/** @internal */
export type PlayQueueGenerator$Outbound = {
  changedAt?: number | undefined;
  createdAt?: number | undefined;
  id?: number | undefined;
  playlistID?: number | undefined;
  type?: number | undefined;
  updatedAt?: number | undefined;
  uri?: string | undefined;
};

/** @internal */
export const PlayQueueGenerator$outboundSchema: z.ZodType<
  PlayQueueGenerator$Outbound,
  z.ZodTypeDef,
  PlayQueueGenerator
> = z.object({
  changedAt: z.number().int().optional(),
  createdAt: z.number().int().optional(),
  id: z.number().int().optional(),
  playlistID: z.number().int().optional(),
  type: GetPlaylistGeneratorsType$outboundSchema.optional(),
  updatedAt: z.number().int().optional(),
  uri: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PlayQueueGenerator$ {
  /** @deprecated use `PlayQueueGenerator$inboundSchema` instead. */
  export const inboundSchema = PlayQueueGenerator$inboundSchema;
  /** @deprecated use `PlayQueueGenerator$outboundSchema` instead. */
  export const outboundSchema = PlayQueueGenerator$outboundSchema;
  /** @deprecated use `PlayQueueGenerator$Outbound` instead. */
  export type Outbound = PlayQueueGenerator$Outbound;
}

export function playQueueGeneratorToJSON(
  playQueueGenerator: PlayQueueGenerator,
): string {
  return JSON.stringify(
    PlayQueueGenerator$outboundSchema.parse(playQueueGenerator),
  );
}

export function playQueueGeneratorFromJSON(
  jsonString: string,
): SafeParseResult<PlayQueueGenerator, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PlayQueueGenerator$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PlayQueueGenerator' from JSON`,
  );
}

/** @internal */
export const GetPlaylistGeneratorsMediaContainer$inboundSchema: z.ZodType<
  GetPlaylistGeneratorsMediaContainer,
  z.ZodTypeDef,
  unknown
> = z.object({
  identifier: z.string().optional(),
  offset: z.number().int().optional(),
  size: z.number().int().optional(),
  totalSize: z.number().int().optional(),
  PlayQueueGenerator: z.array(z.lazy(() => PlayQueueGenerator$inboundSchema))
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "PlayQueueGenerator": "playQueueGenerator",
  });
});

/** @internal */
export type GetPlaylistGeneratorsMediaContainer$Outbound = {
  identifier?: string | undefined;
  offset?: number | undefined;
  size?: number | undefined;
  totalSize?: number | undefined;
  PlayQueueGenerator?: Array<PlayQueueGenerator$Outbound> | undefined;
};

/** @internal */
export const GetPlaylistGeneratorsMediaContainer$outboundSchema: z.ZodType<
  GetPlaylistGeneratorsMediaContainer$Outbound,
  z.ZodTypeDef,
  GetPlaylistGeneratorsMediaContainer
> = z.object({
  identifier: z.string().optional(),
  offset: z.number().int().optional(),
  size: z.number().int().optional(),
  totalSize: z.number().int().optional(),
  playQueueGenerator: z.array(z.lazy(() => PlayQueueGenerator$outboundSchema))
    .optional(),
}).transform((v) => {
  return remap$(v, {
    playQueueGenerator: "PlayQueueGenerator",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetPlaylistGeneratorsMediaContainer$ {
  /** @deprecated use `GetPlaylistGeneratorsMediaContainer$inboundSchema` instead. */
  export const inboundSchema =
    GetPlaylistGeneratorsMediaContainer$inboundSchema;
  /** @deprecated use `GetPlaylistGeneratorsMediaContainer$outboundSchema` instead. */
  export const outboundSchema =
    GetPlaylistGeneratorsMediaContainer$outboundSchema;
  /** @deprecated use `GetPlaylistGeneratorsMediaContainer$Outbound` instead. */
  export type Outbound = GetPlaylistGeneratorsMediaContainer$Outbound;
}

export function getPlaylistGeneratorsMediaContainerToJSON(
  getPlaylistGeneratorsMediaContainer: GetPlaylistGeneratorsMediaContainer,
): string {
  return JSON.stringify(
    GetPlaylistGeneratorsMediaContainer$outboundSchema.parse(
      getPlaylistGeneratorsMediaContainer,
    ),
  );
}

export function getPlaylistGeneratorsMediaContainerFromJSON(
  jsonString: string,
): SafeParseResult<GetPlaylistGeneratorsMediaContainer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetPlaylistGeneratorsMediaContainer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlaylistGeneratorsMediaContainer' from JSON`,
  );
}

/** @internal */
export const GetPlaylistGeneratorsResponseBody$inboundSchema: z.ZodType<
  GetPlaylistGeneratorsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  MediaContainer: z.lazy(() =>
    GetPlaylistGeneratorsMediaContainer$inboundSchema
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    "MediaContainer": "mediaContainer",
  });
});

/** @internal */
export type GetPlaylistGeneratorsResponseBody$Outbound = {
  MediaContainer?: GetPlaylistGeneratorsMediaContainer$Outbound | undefined;
};

/** @internal */
export const GetPlaylistGeneratorsResponseBody$outboundSchema: z.ZodType<
  GetPlaylistGeneratorsResponseBody$Outbound,
  z.ZodTypeDef,
  GetPlaylistGeneratorsResponseBody
> = z.object({
  mediaContainer: z.lazy(() =>
    GetPlaylistGeneratorsMediaContainer$outboundSchema
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    mediaContainer: "MediaContainer",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetPlaylistGeneratorsResponseBody$ {
  /** @deprecated use `GetPlaylistGeneratorsResponseBody$inboundSchema` instead. */
  export const inboundSchema = GetPlaylistGeneratorsResponseBody$inboundSchema;
  /** @deprecated use `GetPlaylistGeneratorsResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    GetPlaylistGeneratorsResponseBody$outboundSchema;
  /** @deprecated use `GetPlaylistGeneratorsResponseBody$Outbound` instead. */
  export type Outbound = GetPlaylistGeneratorsResponseBody$Outbound;
}

export function getPlaylistGeneratorsResponseBodyToJSON(
  getPlaylistGeneratorsResponseBody: GetPlaylistGeneratorsResponseBody,
): string {
  return JSON.stringify(
    GetPlaylistGeneratorsResponseBody$outboundSchema.parse(
      getPlaylistGeneratorsResponseBody,
    ),
  );
}

export function getPlaylistGeneratorsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetPlaylistGeneratorsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPlaylistGeneratorsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlaylistGeneratorsResponseBody' from JSON`,
  );
}

/** @internal */
export const GetPlaylistGeneratorsResponse$inboundSchema: z.ZodType<
  GetPlaylistGeneratorsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
  object: z.lazy(() => GetPlaylistGeneratorsResponseBody$inboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
  });
});

/** @internal */
export type GetPlaylistGeneratorsResponse$Outbound = {
  ContentType: string;
  StatusCode: number;
  RawResponse: never;
  object?: GetPlaylistGeneratorsResponseBody$Outbound | undefined;
};

/** @internal */
export const GetPlaylistGeneratorsResponse$outboundSchema: z.ZodType<
  GetPlaylistGeneratorsResponse$Outbound,
  z.ZodTypeDef,
  GetPlaylistGeneratorsResponse
> = z.object({
  contentType: z.string(),
  statusCode: z.number().int(),
  rawResponse: z.instanceof(Response).transform(() => {
    throw new Error("Response cannot be serialized");
  }),
  object: z.lazy(() => GetPlaylistGeneratorsResponseBody$outboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    contentType: "ContentType",
    statusCode: "StatusCode",
    rawResponse: "RawResponse",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetPlaylistGeneratorsResponse$ {
  /** @deprecated use `GetPlaylistGeneratorsResponse$inboundSchema` instead. */
  export const inboundSchema = GetPlaylistGeneratorsResponse$inboundSchema;
  /** @deprecated use `GetPlaylistGeneratorsResponse$outboundSchema` instead. */
  export const outboundSchema = GetPlaylistGeneratorsResponse$outboundSchema;
  /** @deprecated use `GetPlaylistGeneratorsResponse$Outbound` instead. */
  export type Outbound = GetPlaylistGeneratorsResponse$Outbound;
}

export function getPlaylistGeneratorsResponseToJSON(
  getPlaylistGeneratorsResponse: GetPlaylistGeneratorsResponse,
): string {
  return JSON.stringify(
    GetPlaylistGeneratorsResponse$outboundSchema.parse(
      getPlaylistGeneratorsResponse,
    ),
  );
}

export function getPlaylistGeneratorsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetPlaylistGeneratorsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPlaylistGeneratorsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlaylistGeneratorsResponse' from JSON`,
  );
}
