/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type GetPlayQueueGlobals = {
  /**
   * An opaque identifier unique to the client
   */
  xPlexClientIdentifier?: string | undefined;
  /**
   * The name of the client product
   */
  xPlexProduct?: string | undefined;
  /**
   * The version of the client application
   */
  xPlexVersion?: string | undefined;
  /**
   * The platform of the client
   */
  xPlexPlatform?: string | undefined;
  /**
   * The version of the platform
   */
  xPlexPlatformVersion?: string | undefined;
  /**
   * A relatively friendly name for the client device
   */
  xPlexDevice?: string | undefined;
  /**
   * A potentially less friendly identifier for the device model
   */
  xPlexModel?: string | undefined;
  /**
   * The device vendor
   */
  xPlexDeviceVendor?: string | undefined;
  /**
   * A friendly name for the client
   */
  xPlexDeviceName?: string | undefined;
  /**
   * The marketplace on which the client application is distributed
   */
  xPlexMarketplace?: string | undefined;
};

export type GetPlayQueueRequest = {
  /**
   * An opaque identifier unique to the client
   */
  xPlexClientIdentifier?: string | undefined;
  /**
   * The name of the client product
   */
  xPlexProduct?: string | undefined;
  /**
   * The version of the client application
   */
  xPlexVersion?: string | undefined;
  /**
   * The platform of the client
   */
  xPlexPlatform?: string | undefined;
  /**
   * The version of the platform
   */
  xPlexPlatformVersion?: string | undefined;
  /**
   * A relatively friendly name for the client device
   */
  xPlexDevice?: string | undefined;
  /**
   * A potentially less friendly identifier for the device model
   */
  xPlexModel?: string | undefined;
  /**
   * The device vendor
   */
  xPlexDeviceVendor?: string | undefined;
  /**
   * A friendly name for the client
   */
  xPlexDeviceName?: string | undefined;
  /**
   * The marketplace on which the client application is distributed
   */
  xPlexMarketplace?: string | undefined;
  /**
   * The ID of the play queue.
   */
  playQueueId: number;
  /**
   * If the server should transfer ownership to the requesting client (used in remote control scenarios).
   */
  own?: shared.BoolInt | undefined;
  /**
   * The play queue item ID for the center of the window - this doesn't change the current selected item.
   */
  center?: string | undefined;
  /**
   * How many items on each side of the center of the window
   */
  window?: number | undefined;
  /**
   * Whether to include the items before the center (if 0, center is not included either), defaults to 1.
   */
  includeBefore?: shared.BoolInt | undefined;
  /**
   * Whether to include the items after the center (if 0, center is not included either), defaults to 1.
   */
  includeAfter?: shared.BoolInt | undefined;
};

export type GetPlayQueueResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * OK
   */
  mediaContainerWithPlaylistMetadata?:
    | shared.MediaContainerWithPlaylistMetadata
    | undefined;
};

/** @internal */
export const GetPlayQueueGlobals$inboundSchema: z.ZodType<
  GetPlayQueueGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  "X-Plex-Client-Identifier": z.string().optional(),
  "X-Plex-Product": z.string().optional(),
  "X-Plex-Version": z.string().optional(),
  "X-Plex-Platform": z.string().optional(),
  "X-Plex-Platform-Version": z.string().optional(),
  "X-Plex-Device": z.string().optional(),
  "X-Plex-Model": z.string().optional(),
  "X-Plex-Device-Vendor": z.string().optional(),
  "X-Plex-Device-Name": z.string().optional(),
  "X-Plex-Marketplace": z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "X-Plex-Client-Identifier": "xPlexClientIdentifier",
    "X-Plex-Product": "xPlexProduct",
    "X-Plex-Version": "xPlexVersion",
    "X-Plex-Platform": "xPlexPlatform",
    "X-Plex-Platform-Version": "xPlexPlatformVersion",
    "X-Plex-Device": "xPlexDevice",
    "X-Plex-Model": "xPlexModel",
    "X-Plex-Device-Vendor": "xPlexDeviceVendor",
    "X-Plex-Device-Name": "xPlexDeviceName",
    "X-Plex-Marketplace": "xPlexMarketplace",
  });
});

/** @internal */
export type GetPlayQueueGlobals$Outbound = {
  "X-Plex-Client-Identifier"?: string | undefined;
  "X-Plex-Product"?: string | undefined;
  "X-Plex-Version"?: string | undefined;
  "X-Plex-Platform"?: string | undefined;
  "X-Plex-Platform-Version"?: string | undefined;
  "X-Plex-Device"?: string | undefined;
  "X-Plex-Model"?: string | undefined;
  "X-Plex-Device-Vendor"?: string | undefined;
  "X-Plex-Device-Name"?: string | undefined;
  "X-Plex-Marketplace"?: string | undefined;
};

/** @internal */
export const GetPlayQueueGlobals$outboundSchema: z.ZodType<
  GetPlayQueueGlobals$Outbound,
  z.ZodTypeDef,
  GetPlayQueueGlobals
> = z.object({
  xPlexClientIdentifier: z.string().optional(),
  xPlexProduct: z.string().optional(),
  xPlexVersion: z.string().optional(),
  xPlexPlatform: z.string().optional(),
  xPlexPlatformVersion: z.string().optional(),
  xPlexDevice: z.string().optional(),
  xPlexModel: z.string().optional(),
  xPlexDeviceVendor: z.string().optional(),
  xPlexDeviceName: z.string().optional(),
  xPlexMarketplace: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    xPlexClientIdentifier: "X-Plex-Client-Identifier",
    xPlexProduct: "X-Plex-Product",
    xPlexVersion: "X-Plex-Version",
    xPlexPlatform: "X-Plex-Platform",
    xPlexPlatformVersion: "X-Plex-Platform-Version",
    xPlexDevice: "X-Plex-Device",
    xPlexModel: "X-Plex-Model",
    xPlexDeviceVendor: "X-Plex-Device-Vendor",
    xPlexDeviceName: "X-Plex-Device-Name",
    xPlexMarketplace: "X-Plex-Marketplace",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetPlayQueueGlobals$ {
  /** @deprecated use `GetPlayQueueGlobals$inboundSchema` instead. */
  export const inboundSchema = GetPlayQueueGlobals$inboundSchema;
  /** @deprecated use `GetPlayQueueGlobals$outboundSchema` instead. */
  export const outboundSchema = GetPlayQueueGlobals$outboundSchema;
  /** @deprecated use `GetPlayQueueGlobals$Outbound` instead. */
  export type Outbound = GetPlayQueueGlobals$Outbound;
}

export function getPlayQueueGlobalsToJSON(
  getPlayQueueGlobals: GetPlayQueueGlobals,
): string {
  return JSON.stringify(
    GetPlayQueueGlobals$outboundSchema.parse(getPlayQueueGlobals),
  );
}

export function getPlayQueueGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<GetPlayQueueGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPlayQueueGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlayQueueGlobals' from JSON`,
  );
}

/** @internal */
export const GetPlayQueueRequest$inboundSchema: z.ZodType<
  GetPlayQueueRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  "X-Plex-Client-Identifier": z.string().optional(),
  "X-Plex-Product": z.string().optional(),
  "X-Plex-Version": z.string().optional(),
  "X-Plex-Platform": z.string().optional(),
  "X-Plex-Platform-Version": z.string().optional(),
  "X-Plex-Device": z.string().optional(),
  "X-Plex-Model": z.string().optional(),
  "X-Plex-Device-Vendor": z.string().optional(),
  "X-Plex-Device-Name": z.string().optional(),
  "X-Plex-Marketplace": z.string().optional(),
  playQueueId: z.number().int(),
  own: shared.BoolInt$inboundSchema.optional(),
  center: z.string().optional(),
  window: z.number().int().optional(),
  includeBefore: shared.BoolInt$inboundSchema.optional(),
  includeAfter: shared.BoolInt$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "X-Plex-Client-Identifier": "xPlexClientIdentifier",
    "X-Plex-Product": "xPlexProduct",
    "X-Plex-Version": "xPlexVersion",
    "X-Plex-Platform": "xPlexPlatform",
    "X-Plex-Platform-Version": "xPlexPlatformVersion",
    "X-Plex-Device": "xPlexDevice",
    "X-Plex-Model": "xPlexModel",
    "X-Plex-Device-Vendor": "xPlexDeviceVendor",
    "X-Plex-Device-Name": "xPlexDeviceName",
    "X-Plex-Marketplace": "xPlexMarketplace",
  });
});

/** @internal */
export type GetPlayQueueRequest$Outbound = {
  "X-Plex-Client-Identifier"?: string | undefined;
  "X-Plex-Product"?: string | undefined;
  "X-Plex-Version"?: string | undefined;
  "X-Plex-Platform"?: string | undefined;
  "X-Plex-Platform-Version"?: string | undefined;
  "X-Plex-Device"?: string | undefined;
  "X-Plex-Model"?: string | undefined;
  "X-Plex-Device-Vendor"?: string | undefined;
  "X-Plex-Device-Name"?: string | undefined;
  "X-Plex-Marketplace"?: string | undefined;
  playQueueId: number;
  own?: number | undefined;
  center?: string | undefined;
  window?: number | undefined;
  includeBefore?: number | undefined;
  includeAfter?: number | undefined;
};

/** @internal */
export const GetPlayQueueRequest$outboundSchema: z.ZodType<
  GetPlayQueueRequest$Outbound,
  z.ZodTypeDef,
  GetPlayQueueRequest
> = z.object({
  xPlexClientIdentifier: z.string().optional(),
  xPlexProduct: z.string().optional(),
  xPlexVersion: z.string().optional(),
  xPlexPlatform: z.string().optional(),
  xPlexPlatformVersion: z.string().optional(),
  xPlexDevice: z.string().optional(),
  xPlexModel: z.string().optional(),
  xPlexDeviceVendor: z.string().optional(),
  xPlexDeviceName: z.string().optional(),
  xPlexMarketplace: z.string().optional(),
  playQueueId: z.number().int(),
  own: shared.BoolInt$outboundSchema.optional(),
  center: z.string().optional(),
  window: z.number().int().optional(),
  includeBefore: shared.BoolInt$outboundSchema.optional(),
  includeAfter: shared.BoolInt$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    xPlexClientIdentifier: "X-Plex-Client-Identifier",
    xPlexProduct: "X-Plex-Product",
    xPlexVersion: "X-Plex-Version",
    xPlexPlatform: "X-Plex-Platform",
    xPlexPlatformVersion: "X-Plex-Platform-Version",
    xPlexDevice: "X-Plex-Device",
    xPlexModel: "X-Plex-Model",
    xPlexDeviceVendor: "X-Plex-Device-Vendor",
    xPlexDeviceName: "X-Plex-Device-Name",
    xPlexMarketplace: "X-Plex-Marketplace",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetPlayQueueRequest$ {
  /** @deprecated use `GetPlayQueueRequest$inboundSchema` instead. */
  export const inboundSchema = GetPlayQueueRequest$inboundSchema;
  /** @deprecated use `GetPlayQueueRequest$outboundSchema` instead. */
  export const outboundSchema = GetPlayQueueRequest$outboundSchema;
  /** @deprecated use `GetPlayQueueRequest$Outbound` instead. */
  export type Outbound = GetPlayQueueRequest$Outbound;
}

export function getPlayQueueRequestToJSON(
  getPlayQueueRequest: GetPlayQueueRequest,
): string {
  return JSON.stringify(
    GetPlayQueueRequest$outboundSchema.parse(getPlayQueueRequest),
  );
}

export function getPlayQueueRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetPlayQueueRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPlayQueueRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlayQueueRequest' from JSON`,
  );
}

/** @internal */
export const GetPlayQueueResponse$inboundSchema: z.ZodType<
  GetPlayQueueResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
  MediaContainerWithPlaylistMetadata: shared
    .MediaContainerWithPlaylistMetadata$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
    "MediaContainerWithPlaylistMetadata": "mediaContainerWithPlaylistMetadata",
  });
});

/** @internal */
export type GetPlayQueueResponse$Outbound = {
  ContentType: string;
  StatusCode: number;
  RawResponse: never;
  MediaContainerWithPlaylistMetadata?:
    | shared.MediaContainerWithPlaylistMetadata$Outbound
    | undefined;
};

/** @internal */
export const GetPlayQueueResponse$outboundSchema: z.ZodType<
  GetPlayQueueResponse$Outbound,
  z.ZodTypeDef,
  GetPlayQueueResponse
> = z.object({
  contentType: z.string(),
  statusCode: z.number().int(),
  rawResponse: z.instanceof(Response).transform(() => {
    throw new Error("Response cannot be serialized");
  }),
  mediaContainerWithPlaylistMetadata: shared
    .MediaContainerWithPlaylistMetadata$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    contentType: "ContentType",
    statusCode: "StatusCode",
    rawResponse: "RawResponse",
    mediaContainerWithPlaylistMetadata: "MediaContainerWithPlaylistMetadata",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetPlayQueueResponse$ {
  /** @deprecated use `GetPlayQueueResponse$inboundSchema` instead. */
  export const inboundSchema = GetPlayQueueResponse$inboundSchema;
  /** @deprecated use `GetPlayQueueResponse$outboundSchema` instead. */
  export const outboundSchema = GetPlayQueueResponse$outboundSchema;
  /** @deprecated use `GetPlayQueueResponse$Outbound` instead. */
  export type Outbound = GetPlayQueueResponse$Outbound;
}

export function getPlayQueueResponseToJSON(
  getPlayQueueResponse: GetPlayQueueResponse,
): string {
  return JSON.stringify(
    GetPlayQueueResponse$outboundSchema.parse(getPlayQueueResponse),
  );
}

export function getPlayQueueResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetPlayQueueResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPlayQueueResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlayQueueResponse' from JSON`,
  );
}
