/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type GetPlaylistGeneratorsGlobals = {
  /**
   * Indicates the client accepts the indicated media types
   */
  accepts?: shared.Accepts | undefined;
  /**
   * An opaque identifier unique to the client
   */
  clientIdentifier?: string | undefined;
  /**
   * The name of the client product
   */
  product?: string | undefined;
  /**
   * The version of the client application
   */
  version?: string | undefined;
  /**
   * The platform of the client
   */
  platform?: string | undefined;
  /**
   * The version of the platform
   */
  platformVersion?: string | undefined;
  /**
   * A relatively friendly name for the client device
   */
  device?: string | undefined;
  /**
   * A potentially less friendly identifier for the device model
   */
  model?: string | undefined;
  /**
   * The device vendor
   */
  deviceVendor?: string | undefined;
  /**
   * A friendly name for the client
   */
  deviceName?: string | undefined;
  /**
   * The marketplace on which the client application is distributed
   */
  marketplace?: string | undefined;
};

export type GetPlaylistGeneratorsRequest = {
  /**
   * Indicates the client accepts the indicated media types
   */
  accepts?: shared.Accepts | undefined;
  /**
   * An opaque identifier unique to the client
   */
  clientIdentifier?: string | undefined;
  /**
   * The name of the client product
   */
  product?: string | undefined;
  /**
   * The version of the client application
   */
  version?: string | undefined;
  /**
   * The platform of the client
   */
  platform?: string | undefined;
  /**
   * The version of the platform
   */
  platformVersion?: string | undefined;
  /**
   * A relatively friendly name for the client device
   */
  device?: string | undefined;
  /**
   * A potentially less friendly identifier for the device model
   */
  model?: string | undefined;
  /**
   * The device vendor
   */
  deviceVendor?: string | undefined;
  /**
   * A friendly name for the client
   */
  deviceName?: string | undefined;
  /**
   * The marketplace on which the client application is distributed
   */
  marketplace?: string | undefined;
  /**
   * The ID of the playlist
   */
  playlistId: number;
};

/**
 * The type of playlist generator.
 *
 * @remarks
 *
 *   - -1: A smart playlist generator
 *   - 42: A optimized version generator
 */
export enum GetPlaylistGeneratorsType {
  Minus1 = -1,
  FortyTwo = 42,
}

export type PlayQueueGenerator = {
  changedAt?: number | undefined;
  createdAt?: number | undefined;
  id?: number | undefined;
  playlistID?: number | undefined;
  /**
   * The type of playlist generator.
   *
   * @remarks
   *
   *   - -1: A smart playlist generator
   *   - 42: A optimized version generator
   */
  type?: GetPlaylistGeneratorsType | undefined;
  updatedAt?: number | undefined;
  /**
   * The URI indicating the search for this generator
   */
  uri?: string | undefined;
};

/**
 * `MediaContainer` is the root element of most Plex API responses. It serves as a generic container for various types of content (Metadata, Hubs, Directories, etc.) and includes pagination information (offset, size, totalSize) when applicable.
 *
 * @remarks
 * Common attributes: - identifier: Unique identifier for this container - size: Number of items in this response page - totalSize: Total number of items available (for pagination) - offset: Starting index of this page (for pagination)
 * The container often "hoists" common attributes from its children. For example, if all tracks in a container share the same album title, the `parentTitle` attribute may appear on the MediaContainer rather than being repeated on each track.
 */
export type GetPlaylistGeneratorsMediaContainer = {
  identifier?: string | undefined;
  /**
   * The offset of where this container page starts among the total objects available. Also provided in the `X-Plex-Container-Start` header.
   *
   * @remarks
   */
  offset?: number | undefined;
  size?: number | undefined;
  /**
   * The total size of objects available. Also provided in the `X-Plex-Container-Total-Size` header.
   *
   * @remarks
   */
  totalSize?: number | undefined;
  playQueueGenerator?: Array<PlayQueueGenerator> | undefined;
};

/**
 * OK
 */
export type GetPlaylistGeneratorsResponseBody = {
  mediaContainer?: GetPlaylistGeneratorsMediaContainer | undefined;
};

export type GetPlaylistGeneratorsResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * OK
   */
  object?: GetPlaylistGeneratorsResponseBody | undefined;
};

/** @internal */
export type GetPlaylistGeneratorsRequest$Outbound = {
  accepts: string;
  "Client-Identifier"?: string | undefined;
  Product?: string | undefined;
  Version?: string | undefined;
  Platform?: string | undefined;
  "Platform-Version"?: string | undefined;
  Device?: string | undefined;
  Model?: string | undefined;
  "Device-Vendor"?: string | undefined;
  "Device-Name"?: string | undefined;
  Marketplace?: string | undefined;
  playlistId: number;
};

/** @internal */
export const GetPlaylistGeneratorsRequest$outboundSchema: z.ZodType<
  GetPlaylistGeneratorsRequest$Outbound,
  z.ZodTypeDef,
  GetPlaylistGeneratorsRequest
> = z.object({
  accepts: shared.Accepts$outboundSchema.default(shared.Accepts.ApplicationXml),
  clientIdentifier: z.string().optional(),
  product: z.string().optional(),
  version: z.string().optional(),
  platform: z.string().optional(),
  platformVersion: z.string().optional(),
  device: z.string().optional(),
  model: z.string().optional(),
  deviceVendor: z.string().optional(),
  deviceName: z.string().optional(),
  marketplace: z.string().optional(),
  playlistId: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    clientIdentifier: "Client-Identifier",
    product: "Product",
    version: "Version",
    platform: "Platform",
    platformVersion: "Platform-Version",
    device: "Device",
    model: "Model",
    deviceVendor: "Device-Vendor",
    deviceName: "Device-Name",
    marketplace: "Marketplace",
  });
});

export function getPlaylistGeneratorsRequestToJSON(
  getPlaylistGeneratorsRequest: GetPlaylistGeneratorsRequest,
): string {
  return JSON.stringify(
    GetPlaylistGeneratorsRequest$outboundSchema.parse(
      getPlaylistGeneratorsRequest,
    ),
  );
}

/** @internal */
export const GetPlaylistGeneratorsType$inboundSchema: z.ZodNativeEnum<
  typeof GetPlaylistGeneratorsType
> = z.nativeEnum(GetPlaylistGeneratorsType);

/** @internal */
export const PlayQueueGenerator$inboundSchema: z.ZodType<
  PlayQueueGenerator,
  z.ZodTypeDef,
  unknown
> = z.object({
  changedAt: z.number().int().optional(),
  createdAt: z.number().int().optional(),
  id: z.number().int().optional(),
  playlistID: z.number().int().optional(),
  type: GetPlaylistGeneratorsType$inboundSchema.optional(),
  updatedAt: z.number().int().optional(),
  uri: z.string().optional(),
});

export function playQueueGeneratorFromJSON(
  jsonString: string,
): SafeParseResult<PlayQueueGenerator, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PlayQueueGenerator$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PlayQueueGenerator' from JSON`,
  );
}

/** @internal */
export const GetPlaylistGeneratorsMediaContainer$inboundSchema: z.ZodType<
  GetPlaylistGeneratorsMediaContainer,
  z.ZodTypeDef,
  unknown
> = z.object({
  identifier: z.string().optional(),
  offset: z.number().int().optional(),
  size: z.number().int().optional(),
  totalSize: z.number().int().optional(),
  PlayQueueGenerator: z.array(z.lazy(() => PlayQueueGenerator$inboundSchema))
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "PlayQueueGenerator": "playQueueGenerator",
  });
});

export function getPlaylistGeneratorsMediaContainerFromJSON(
  jsonString: string,
): SafeParseResult<GetPlaylistGeneratorsMediaContainer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetPlaylistGeneratorsMediaContainer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlaylistGeneratorsMediaContainer' from JSON`,
  );
}

/** @internal */
export const GetPlaylistGeneratorsResponseBody$inboundSchema: z.ZodType<
  GetPlaylistGeneratorsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  MediaContainer: z.lazy(() =>
    GetPlaylistGeneratorsMediaContainer$inboundSchema
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    "MediaContainer": "mediaContainer",
  });
});

export function getPlaylistGeneratorsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetPlaylistGeneratorsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPlaylistGeneratorsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlaylistGeneratorsResponseBody' from JSON`,
  );
}

/** @internal */
export const GetPlaylistGeneratorsResponse$inboundSchema: z.ZodType<
  GetPlaylistGeneratorsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
  object: z.lazy(() => GetPlaylistGeneratorsResponseBody$inboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
  });
});

export function getPlaylistGeneratorsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetPlaylistGeneratorsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPlaylistGeneratorsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlaylistGeneratorsResponse' from JSON`,
  );
}
