/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type ListPlaylistsGlobals = {
  /**
   * An opaque identifier unique to the client
   */
  xPlexClientIdentifier?: string | undefined;
  /**
   * The name of the client product
   */
  xPlexProduct?: string | undefined;
  /**
   * The version of the client application
   */
  xPlexVersion?: string | undefined;
  /**
   * The platform of the client
   */
  xPlexPlatform?: string | undefined;
  /**
   * The version of the platform
   */
  xPlexPlatformVersion?: string | undefined;
  /**
   * A relatively friendly name for the client device
   */
  xPlexDevice?: string | undefined;
  /**
   * A potentially less friendly identifier for the device model
   */
  xPlexModel?: string | undefined;
  /**
   * The device vendor
   */
  xPlexDeviceVendor?: string | undefined;
  /**
   * A friendly name for the client
   */
  xPlexDeviceName?: string | undefined;
  /**
   * The marketplace on which the client application is distributed
   */
  xPlexMarketplace?: string | undefined;
};

/**
 * Limit to a type of playlist
 */
export enum PlaylistType {
  Audio = "audio",
  Video = "video",
  Photo = "photo",
}

export type ListPlaylistsRequest = {
  /**
   * An opaque identifier unique to the client
   */
  xPlexClientIdentifier?: string | undefined;
  /**
   * The name of the client product
   */
  xPlexProduct?: string | undefined;
  /**
   * The version of the client application
   */
  xPlexVersion?: string | undefined;
  /**
   * The platform of the client
   */
  xPlexPlatform?: string | undefined;
  /**
   * The version of the platform
   */
  xPlexPlatformVersion?: string | undefined;
  /**
   * A relatively friendly name for the client device
   */
  xPlexDevice?: string | undefined;
  /**
   * A potentially less friendly identifier for the device model
   */
  xPlexModel?: string | undefined;
  /**
   * The device vendor
   */
  xPlexDeviceVendor?: string | undefined;
  /**
   * A friendly name for the client
   */
  xPlexDeviceName?: string | undefined;
  /**
   * The marketplace on which the client application is distributed
   */
  xPlexMarketplace?: string | undefined;
  /**
   * Limit to a type of playlist
   */
  playlistType?: PlaylistType | undefined;
  /**
   * Whether this is a smart collection/playlist
   */
  smart?: boolean | undefined;
};

export type ListPlaylistsResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * OK
   */
  mediaContainerWithPlaylistMetadata?:
    | shared.MediaContainerWithPlaylistMetadata
    | undefined;
  headers: { [k: string]: Array<string> };
};

/** @internal */
export const ListPlaylistsGlobals$inboundSchema: z.ZodType<
  ListPlaylistsGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  "X-Plex-Client-Identifier": z.string().optional(),
  "X-Plex-Product": z.string().optional(),
  "X-Plex-Version": z.string().optional(),
  "X-Plex-Platform": z.string().optional(),
  "X-Plex-Platform-Version": z.string().optional(),
  "X-Plex-Device": z.string().optional(),
  "X-Plex-Model": z.string().optional(),
  "X-Plex-Device-Vendor": z.string().optional(),
  "X-Plex-Device-Name": z.string().optional(),
  "X-Plex-Marketplace": z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "X-Plex-Client-Identifier": "xPlexClientIdentifier",
    "X-Plex-Product": "xPlexProduct",
    "X-Plex-Version": "xPlexVersion",
    "X-Plex-Platform": "xPlexPlatform",
    "X-Plex-Platform-Version": "xPlexPlatformVersion",
    "X-Plex-Device": "xPlexDevice",
    "X-Plex-Model": "xPlexModel",
    "X-Plex-Device-Vendor": "xPlexDeviceVendor",
    "X-Plex-Device-Name": "xPlexDeviceName",
    "X-Plex-Marketplace": "xPlexMarketplace",
  });
});

/** @internal */
export type ListPlaylistsGlobals$Outbound = {
  "X-Plex-Client-Identifier"?: string | undefined;
  "X-Plex-Product"?: string | undefined;
  "X-Plex-Version"?: string | undefined;
  "X-Plex-Platform"?: string | undefined;
  "X-Plex-Platform-Version"?: string | undefined;
  "X-Plex-Device"?: string | undefined;
  "X-Plex-Model"?: string | undefined;
  "X-Plex-Device-Vendor"?: string | undefined;
  "X-Plex-Device-Name"?: string | undefined;
  "X-Plex-Marketplace"?: string | undefined;
};

/** @internal */
export const ListPlaylistsGlobals$outboundSchema: z.ZodType<
  ListPlaylistsGlobals$Outbound,
  z.ZodTypeDef,
  ListPlaylistsGlobals
> = z.object({
  xPlexClientIdentifier: z.string().optional(),
  xPlexProduct: z.string().optional(),
  xPlexVersion: z.string().optional(),
  xPlexPlatform: z.string().optional(),
  xPlexPlatformVersion: z.string().optional(),
  xPlexDevice: z.string().optional(),
  xPlexModel: z.string().optional(),
  xPlexDeviceVendor: z.string().optional(),
  xPlexDeviceName: z.string().optional(),
  xPlexMarketplace: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    xPlexClientIdentifier: "X-Plex-Client-Identifier",
    xPlexProduct: "X-Plex-Product",
    xPlexVersion: "X-Plex-Version",
    xPlexPlatform: "X-Plex-Platform",
    xPlexPlatformVersion: "X-Plex-Platform-Version",
    xPlexDevice: "X-Plex-Device",
    xPlexModel: "X-Plex-Model",
    xPlexDeviceVendor: "X-Plex-Device-Vendor",
    xPlexDeviceName: "X-Plex-Device-Name",
    xPlexMarketplace: "X-Plex-Marketplace",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListPlaylistsGlobals$ {
  /** @deprecated use `ListPlaylistsGlobals$inboundSchema` instead. */
  export const inboundSchema = ListPlaylistsGlobals$inboundSchema;
  /** @deprecated use `ListPlaylistsGlobals$outboundSchema` instead. */
  export const outboundSchema = ListPlaylistsGlobals$outboundSchema;
  /** @deprecated use `ListPlaylistsGlobals$Outbound` instead. */
  export type Outbound = ListPlaylistsGlobals$Outbound;
}

export function listPlaylistsGlobalsToJSON(
  listPlaylistsGlobals: ListPlaylistsGlobals,
): string {
  return JSON.stringify(
    ListPlaylistsGlobals$outboundSchema.parse(listPlaylistsGlobals),
  );
}

export function listPlaylistsGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<ListPlaylistsGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListPlaylistsGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListPlaylistsGlobals' from JSON`,
  );
}

/** @internal */
export const PlaylistType$inboundSchema: z.ZodNativeEnum<typeof PlaylistType> =
  z.nativeEnum(PlaylistType);

/** @internal */
export const PlaylistType$outboundSchema: z.ZodNativeEnum<typeof PlaylistType> =
  PlaylistType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PlaylistType$ {
  /** @deprecated use `PlaylistType$inboundSchema` instead. */
  export const inboundSchema = PlaylistType$inboundSchema;
  /** @deprecated use `PlaylistType$outboundSchema` instead. */
  export const outboundSchema = PlaylistType$outboundSchema;
}

/** @internal */
export const ListPlaylistsRequest$inboundSchema: z.ZodType<
  ListPlaylistsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  "X-Plex-Client-Identifier": z.string().optional(),
  "X-Plex-Product": z.string().optional(),
  "X-Plex-Version": z.string().optional(),
  "X-Plex-Platform": z.string().optional(),
  "X-Plex-Platform-Version": z.string().optional(),
  "X-Plex-Device": z.string().optional(),
  "X-Plex-Model": z.string().optional(),
  "X-Plex-Device-Vendor": z.string().optional(),
  "X-Plex-Device-Name": z.string().optional(),
  "X-Plex-Marketplace": z.string().optional(),
  playlistType: PlaylistType$inboundSchema.optional(),
  smart: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    "X-Plex-Client-Identifier": "xPlexClientIdentifier",
    "X-Plex-Product": "xPlexProduct",
    "X-Plex-Version": "xPlexVersion",
    "X-Plex-Platform": "xPlexPlatform",
    "X-Plex-Platform-Version": "xPlexPlatformVersion",
    "X-Plex-Device": "xPlexDevice",
    "X-Plex-Model": "xPlexModel",
    "X-Plex-Device-Vendor": "xPlexDeviceVendor",
    "X-Plex-Device-Name": "xPlexDeviceName",
    "X-Plex-Marketplace": "xPlexMarketplace",
  });
});

/** @internal */
export type ListPlaylistsRequest$Outbound = {
  "X-Plex-Client-Identifier"?: string | undefined;
  "X-Plex-Product"?: string | undefined;
  "X-Plex-Version"?: string | undefined;
  "X-Plex-Platform"?: string | undefined;
  "X-Plex-Platform-Version"?: string | undefined;
  "X-Plex-Device"?: string | undefined;
  "X-Plex-Model"?: string | undefined;
  "X-Plex-Device-Vendor"?: string | undefined;
  "X-Plex-Device-Name"?: string | undefined;
  "X-Plex-Marketplace"?: string | undefined;
  playlistType?: string | undefined;
  smart?: boolean | undefined;
};

/** @internal */
export const ListPlaylistsRequest$outboundSchema: z.ZodType<
  ListPlaylistsRequest$Outbound,
  z.ZodTypeDef,
  ListPlaylistsRequest
> = z.object({
  xPlexClientIdentifier: z.string().optional(),
  xPlexProduct: z.string().optional(),
  xPlexVersion: z.string().optional(),
  xPlexPlatform: z.string().optional(),
  xPlexPlatformVersion: z.string().optional(),
  xPlexDevice: z.string().optional(),
  xPlexModel: z.string().optional(),
  xPlexDeviceVendor: z.string().optional(),
  xPlexDeviceName: z.string().optional(),
  xPlexMarketplace: z.string().optional(),
  playlistType: PlaylistType$outboundSchema.optional(),
  smart: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    xPlexClientIdentifier: "X-Plex-Client-Identifier",
    xPlexProduct: "X-Plex-Product",
    xPlexVersion: "X-Plex-Version",
    xPlexPlatform: "X-Plex-Platform",
    xPlexPlatformVersion: "X-Plex-Platform-Version",
    xPlexDevice: "X-Plex-Device",
    xPlexModel: "X-Plex-Model",
    xPlexDeviceVendor: "X-Plex-Device-Vendor",
    xPlexDeviceName: "X-Plex-Device-Name",
    xPlexMarketplace: "X-Plex-Marketplace",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListPlaylistsRequest$ {
  /** @deprecated use `ListPlaylistsRequest$inboundSchema` instead. */
  export const inboundSchema = ListPlaylistsRequest$inboundSchema;
  /** @deprecated use `ListPlaylistsRequest$outboundSchema` instead. */
  export const outboundSchema = ListPlaylistsRequest$outboundSchema;
  /** @deprecated use `ListPlaylistsRequest$Outbound` instead. */
  export type Outbound = ListPlaylistsRequest$Outbound;
}

export function listPlaylistsRequestToJSON(
  listPlaylistsRequest: ListPlaylistsRequest,
): string {
  return JSON.stringify(
    ListPlaylistsRequest$outboundSchema.parse(listPlaylistsRequest),
  );
}

export function listPlaylistsRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListPlaylistsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListPlaylistsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListPlaylistsRequest' from JSON`,
  );
}

/** @internal */
export const ListPlaylistsResponse$inboundSchema: z.ZodType<
  ListPlaylistsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
  MediaContainerWithPlaylistMetadata: shared
    .MediaContainerWithPlaylistMetadata$inboundSchema.optional(),
  Headers: z.record(z.array(z.string())),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
    "MediaContainerWithPlaylistMetadata": "mediaContainerWithPlaylistMetadata",
    "Headers": "headers",
  });
});

/** @internal */
export type ListPlaylistsResponse$Outbound = {
  ContentType: string;
  StatusCode: number;
  RawResponse: never;
  MediaContainerWithPlaylistMetadata?:
    | shared.MediaContainerWithPlaylistMetadata$Outbound
    | undefined;
  Headers: { [k: string]: Array<string> };
};

/** @internal */
export const ListPlaylistsResponse$outboundSchema: z.ZodType<
  ListPlaylistsResponse$Outbound,
  z.ZodTypeDef,
  ListPlaylistsResponse
> = z.object({
  contentType: z.string(),
  statusCode: z.number().int(),
  rawResponse: z.instanceof(Response).transform(() => {
    throw new Error("Response cannot be serialized");
  }),
  mediaContainerWithPlaylistMetadata: shared
    .MediaContainerWithPlaylistMetadata$outboundSchema.optional(),
  headers: z.record(z.array(z.string())),
}).transform((v) => {
  return remap$(v, {
    contentType: "ContentType",
    statusCode: "StatusCode",
    rawResponse: "RawResponse",
    mediaContainerWithPlaylistMetadata: "MediaContainerWithPlaylistMetadata",
    headers: "Headers",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListPlaylistsResponse$ {
  /** @deprecated use `ListPlaylistsResponse$inboundSchema` instead. */
  export const inboundSchema = ListPlaylistsResponse$inboundSchema;
  /** @deprecated use `ListPlaylistsResponse$outboundSchema` instead. */
  export const outboundSchema = ListPlaylistsResponse$outboundSchema;
  /** @deprecated use `ListPlaylistsResponse$Outbound` instead. */
  export type Outbound = ListPlaylistsResponse$Outbound;
}

export function listPlaylistsResponseToJSON(
  listPlaylistsResponse: ListPlaylistsResponse,
): string {
  return JSON.stringify(
    ListPlaylistsResponse$outboundSchema.parse(listPlaylistsResponse),
  );
}

export function listPlaylistsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListPlaylistsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListPlaylistsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListPlaylistsResponse' from JSON`,
  );
}
