/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type RefreshSectionGlobals = {
  /**
   * An opaque identifier unique to the client
   */
  xPlexClientIdentifier?: string | undefined;
  /**
   * The name of the client product
   */
  xPlexProduct?: string | undefined;
  /**
   * The version of the client application
   */
  xPlexVersion?: string | undefined;
  /**
   * The platform of the client
   */
  xPlexPlatform?: string | undefined;
  /**
   * The version of the platform
   */
  xPlexPlatformVersion?: string | undefined;
  /**
   * A relatively friendly name for the client device
   */
  xPlexDevice?: string | undefined;
  /**
   * A potentially less friendly identifier for the device model
   */
  xPlexModel?: string | undefined;
  /**
   * The device vendor
   */
  xPlexDeviceVendor?: string | undefined;
  /**
   * A friendly name for the client
   */
  xPlexDeviceName?: string | undefined;
  /**
   * The marketplace on which the client application is distributed
   */
  xPlexMarketplace?: string | undefined;
};

export type RefreshSectionRequest = {
  /**
   * An opaque identifier unique to the client
   */
  xPlexClientIdentifier?: string | undefined;
  /**
   * The name of the client product
   */
  xPlexProduct?: string | undefined;
  /**
   * The version of the client application
   */
  xPlexVersion?: string | undefined;
  /**
   * The platform of the client
   */
  xPlexPlatform?: string | undefined;
  /**
   * The version of the platform
   */
  xPlexPlatformVersion?: string | undefined;
  /**
   * A relatively friendly name for the client device
   */
  xPlexDevice?: string | undefined;
  /**
   * A potentially less friendly identifier for the device model
   */
  xPlexModel?: string | undefined;
  /**
   * The device vendor
   */
  xPlexDeviceVendor?: string | undefined;
  /**
   * A friendly name for the client
   */
  xPlexDeviceName?: string | undefined;
  /**
   * The marketplace on which the client application is distributed
   */
  xPlexMarketplace?: string | undefined;
  /**
   * Section identifier
   */
  sectionId: number;
  /**
   * Whether the update of metadata and items should be performed even if modification dates indicate the items have not change
   */
  force?: shared.BoolInt | undefined;
  /**
   * Restrict refresh to the specified path
   */
  path?: string | undefined;
};

export type RefreshSectionResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
};

/** @internal */
export const RefreshSectionGlobals$inboundSchema: z.ZodType<
  RefreshSectionGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  "X-Plex-Client-Identifier": z.string().optional(),
  "X-Plex-Product": z.string().optional(),
  "X-Plex-Version": z.string().optional(),
  "X-Plex-Platform": z.string().optional(),
  "X-Plex-Platform-Version": z.string().optional(),
  "X-Plex-Device": z.string().optional(),
  "X-Plex-Model": z.string().optional(),
  "X-Plex-Device-Vendor": z.string().optional(),
  "X-Plex-Device-Name": z.string().optional(),
  "X-Plex-Marketplace": z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "X-Plex-Client-Identifier": "xPlexClientIdentifier",
    "X-Plex-Product": "xPlexProduct",
    "X-Plex-Version": "xPlexVersion",
    "X-Plex-Platform": "xPlexPlatform",
    "X-Plex-Platform-Version": "xPlexPlatformVersion",
    "X-Plex-Device": "xPlexDevice",
    "X-Plex-Model": "xPlexModel",
    "X-Plex-Device-Vendor": "xPlexDeviceVendor",
    "X-Plex-Device-Name": "xPlexDeviceName",
    "X-Plex-Marketplace": "xPlexMarketplace",
  });
});

/** @internal */
export type RefreshSectionGlobals$Outbound = {
  "X-Plex-Client-Identifier"?: string | undefined;
  "X-Plex-Product"?: string | undefined;
  "X-Plex-Version"?: string | undefined;
  "X-Plex-Platform"?: string | undefined;
  "X-Plex-Platform-Version"?: string | undefined;
  "X-Plex-Device"?: string | undefined;
  "X-Plex-Model"?: string | undefined;
  "X-Plex-Device-Vendor"?: string | undefined;
  "X-Plex-Device-Name"?: string | undefined;
  "X-Plex-Marketplace"?: string | undefined;
};

/** @internal */
export const RefreshSectionGlobals$outboundSchema: z.ZodType<
  RefreshSectionGlobals$Outbound,
  z.ZodTypeDef,
  RefreshSectionGlobals
> = z.object({
  xPlexClientIdentifier: z.string().optional(),
  xPlexProduct: z.string().optional(),
  xPlexVersion: z.string().optional(),
  xPlexPlatform: z.string().optional(),
  xPlexPlatformVersion: z.string().optional(),
  xPlexDevice: z.string().optional(),
  xPlexModel: z.string().optional(),
  xPlexDeviceVendor: z.string().optional(),
  xPlexDeviceName: z.string().optional(),
  xPlexMarketplace: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    xPlexClientIdentifier: "X-Plex-Client-Identifier",
    xPlexProduct: "X-Plex-Product",
    xPlexVersion: "X-Plex-Version",
    xPlexPlatform: "X-Plex-Platform",
    xPlexPlatformVersion: "X-Plex-Platform-Version",
    xPlexDevice: "X-Plex-Device",
    xPlexModel: "X-Plex-Model",
    xPlexDeviceVendor: "X-Plex-Device-Vendor",
    xPlexDeviceName: "X-Plex-Device-Name",
    xPlexMarketplace: "X-Plex-Marketplace",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RefreshSectionGlobals$ {
  /** @deprecated use `RefreshSectionGlobals$inboundSchema` instead. */
  export const inboundSchema = RefreshSectionGlobals$inboundSchema;
  /** @deprecated use `RefreshSectionGlobals$outboundSchema` instead. */
  export const outboundSchema = RefreshSectionGlobals$outboundSchema;
  /** @deprecated use `RefreshSectionGlobals$Outbound` instead. */
  export type Outbound = RefreshSectionGlobals$Outbound;
}

export function refreshSectionGlobalsToJSON(
  refreshSectionGlobals: RefreshSectionGlobals,
): string {
  return JSON.stringify(
    RefreshSectionGlobals$outboundSchema.parse(refreshSectionGlobals),
  );
}

export function refreshSectionGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<RefreshSectionGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RefreshSectionGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RefreshSectionGlobals' from JSON`,
  );
}

/** @internal */
export const RefreshSectionRequest$inboundSchema: z.ZodType<
  RefreshSectionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  "X-Plex-Client-Identifier": z.string().optional(),
  "X-Plex-Product": z.string().optional(),
  "X-Plex-Version": z.string().optional(),
  "X-Plex-Platform": z.string().optional(),
  "X-Plex-Platform-Version": z.string().optional(),
  "X-Plex-Device": z.string().optional(),
  "X-Plex-Model": z.string().optional(),
  "X-Plex-Device-Vendor": z.string().optional(),
  "X-Plex-Device-Name": z.string().optional(),
  "X-Plex-Marketplace": z.string().optional(),
  sectionId: z.number().int(),
  force: shared.BoolInt$inboundSchema.optional(),
  path: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "X-Plex-Client-Identifier": "xPlexClientIdentifier",
    "X-Plex-Product": "xPlexProduct",
    "X-Plex-Version": "xPlexVersion",
    "X-Plex-Platform": "xPlexPlatform",
    "X-Plex-Platform-Version": "xPlexPlatformVersion",
    "X-Plex-Device": "xPlexDevice",
    "X-Plex-Model": "xPlexModel",
    "X-Plex-Device-Vendor": "xPlexDeviceVendor",
    "X-Plex-Device-Name": "xPlexDeviceName",
    "X-Plex-Marketplace": "xPlexMarketplace",
  });
});

/** @internal */
export type RefreshSectionRequest$Outbound = {
  "X-Plex-Client-Identifier"?: string | undefined;
  "X-Plex-Product"?: string | undefined;
  "X-Plex-Version"?: string | undefined;
  "X-Plex-Platform"?: string | undefined;
  "X-Plex-Platform-Version"?: string | undefined;
  "X-Plex-Device"?: string | undefined;
  "X-Plex-Model"?: string | undefined;
  "X-Plex-Device-Vendor"?: string | undefined;
  "X-Plex-Device-Name"?: string | undefined;
  "X-Plex-Marketplace"?: string | undefined;
  sectionId: number;
  force?: number | undefined;
  path?: string | undefined;
};

/** @internal */
export const RefreshSectionRequest$outboundSchema: z.ZodType<
  RefreshSectionRequest$Outbound,
  z.ZodTypeDef,
  RefreshSectionRequest
> = z.object({
  xPlexClientIdentifier: z.string().optional(),
  xPlexProduct: z.string().optional(),
  xPlexVersion: z.string().optional(),
  xPlexPlatform: z.string().optional(),
  xPlexPlatformVersion: z.string().optional(),
  xPlexDevice: z.string().optional(),
  xPlexModel: z.string().optional(),
  xPlexDeviceVendor: z.string().optional(),
  xPlexDeviceName: z.string().optional(),
  xPlexMarketplace: z.string().optional(),
  sectionId: z.number().int(),
  force: shared.BoolInt$outboundSchema.optional(),
  path: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    xPlexClientIdentifier: "X-Plex-Client-Identifier",
    xPlexProduct: "X-Plex-Product",
    xPlexVersion: "X-Plex-Version",
    xPlexPlatform: "X-Plex-Platform",
    xPlexPlatformVersion: "X-Plex-Platform-Version",
    xPlexDevice: "X-Plex-Device",
    xPlexModel: "X-Plex-Model",
    xPlexDeviceVendor: "X-Plex-Device-Vendor",
    xPlexDeviceName: "X-Plex-Device-Name",
    xPlexMarketplace: "X-Plex-Marketplace",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RefreshSectionRequest$ {
  /** @deprecated use `RefreshSectionRequest$inboundSchema` instead. */
  export const inboundSchema = RefreshSectionRequest$inboundSchema;
  /** @deprecated use `RefreshSectionRequest$outboundSchema` instead. */
  export const outboundSchema = RefreshSectionRequest$outboundSchema;
  /** @deprecated use `RefreshSectionRequest$Outbound` instead. */
  export type Outbound = RefreshSectionRequest$Outbound;
}

export function refreshSectionRequestToJSON(
  refreshSectionRequest: RefreshSectionRequest,
): string {
  return JSON.stringify(
    RefreshSectionRequest$outboundSchema.parse(refreshSectionRequest),
  );
}

export function refreshSectionRequestFromJSON(
  jsonString: string,
): SafeParseResult<RefreshSectionRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RefreshSectionRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RefreshSectionRequest' from JSON`,
  );
}

/** @internal */
export const RefreshSectionResponse$inboundSchema: z.ZodType<
  RefreshSectionResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
  });
});

/** @internal */
export type RefreshSectionResponse$Outbound = {
  ContentType: string;
  StatusCode: number;
  RawResponse: never;
};

/** @internal */
export const RefreshSectionResponse$outboundSchema: z.ZodType<
  RefreshSectionResponse$Outbound,
  z.ZodTypeDef,
  RefreshSectionResponse
> = z.object({
  contentType: z.string(),
  statusCode: z.number().int(),
  rawResponse: z.instanceof(Response).transform(() => {
    throw new Error("Response cannot be serialized");
  }),
}).transform((v) => {
  return remap$(v, {
    contentType: "ContentType",
    statusCode: "StatusCode",
    rawResponse: "RawResponse",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RefreshSectionResponse$ {
  /** @deprecated use `RefreshSectionResponse$inboundSchema` instead. */
  export const inboundSchema = RefreshSectionResponse$inboundSchema;
  /** @deprecated use `RefreshSectionResponse$outboundSchema` instead. */
  export const outboundSchema = RefreshSectionResponse$outboundSchema;
  /** @deprecated use `RefreshSectionResponse$Outbound` instead. */
  export type Outbound = RefreshSectionResponse$Outbound;
}

export function refreshSectionResponseToJSON(
  refreshSectionResponse: RefreshSectionResponse,
): string {
  return JSON.stringify(
    RefreshSectionResponse$outboundSchema.parse(refreshSectionResponse),
  );
}

export function refreshSectionResponseFromJSON(
  jsonString: string,
): SafeParseResult<RefreshSectionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RefreshSectionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RefreshSectionResponse' from JSON`,
  );
}
