/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type SetChannelmapGlobals = {
  /**
   * Indicates the client accepts the indicated media types
   */
  accepts?: shared.Accepts | undefined;
  /**
   * An opaque identifier unique to the client
   */
  clientIdentifier?: string | undefined;
  /**
   * The name of the client product
   */
  product?: string | undefined;
  /**
   * The version of the client application
   */
  version?: string | undefined;
  /**
   * The platform of the client
   */
  platform?: string | undefined;
  /**
   * The version of the platform
   */
  platformVersion?: string | undefined;
  /**
   * A relatively friendly name for the client device
   */
  device?: string | undefined;
  /**
   * A potentially less friendly identifier for the device model
   */
  model?: string | undefined;
  /**
   * The device vendor
   */
  deviceVendor?: string | undefined;
  /**
   * A friendly name for the client
   */
  deviceName?: string | undefined;
  /**
   * The marketplace on which the client application is distributed
   */
  marketplace?: string | undefined;
};

/**
 * The mapping of changes, passed as a map of device channel to lineup VCN.
 */
export type SetChannelmapChannelMapping = {};

/**
 * The mapping of changes, passed as a map of device channel to lineup key.
 */
export type ChannelMappingByKey = {};

export type SetChannelmapRequest = {
  /**
   * Indicates the client accepts the indicated media types
   */
  accepts?: shared.Accepts | undefined;
  /**
   * An opaque identifier unique to the client
   */
  clientIdentifier?: string | undefined;
  /**
   * The name of the client product
   */
  product?: string | undefined;
  /**
   * The version of the client application
   */
  version?: string | undefined;
  /**
   * The platform of the client
   */
  platform?: string | undefined;
  /**
   * The version of the platform
   */
  platformVersion?: string | undefined;
  /**
   * A relatively friendly name for the client device
   */
  device?: string | undefined;
  /**
   * A potentially less friendly identifier for the device model
   */
  model?: string | undefined;
  /**
   * The device vendor
   */
  deviceVendor?: string | undefined;
  /**
   * A friendly name for the client
   */
  deviceName?: string | undefined;
  /**
   * The marketplace on which the client application is distributed
   */
  marketplace?: string | undefined;
  /**
   * The ID of the device.
   */
  deviceId: number;
  /**
   * The mapping of changes, passed as a map of device channel to lineup VCN.
   */
  channelMapping?: SetChannelmapChannelMapping | undefined;
  /**
   * The mapping of changes, passed as a map of device channel to lineup key.
   */
  channelMappingByKey?: ChannelMappingByKey | undefined;
  /**
   * The channels which are enabled.
   */
  channelsEnabled?: Array<string> | undefined;
};

export type SetChannelmapResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * OK
   */
  mediaContainerWithDevice?: shared.MediaContainerWithDevice | undefined;
};

/** @internal */
export const SetChannelmapGlobals$inboundSchema: z.ZodType<
  SetChannelmapGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  accepts: shared.Accepts$inboundSchema.default(shared.Accepts.ApplicationXml),
  "Client-Identifier": z.string().optional(),
  Product: z.string().optional(),
  Version: z.string().optional(),
  Platform: z.string().optional(),
  "Platform-Version": z.string().optional(),
  Device: z.string().optional(),
  Model: z.string().optional(),
  "Device-Vendor": z.string().optional(),
  "Device-Name": z.string().optional(),
  Marketplace: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "Client-Identifier": "clientIdentifier",
    "Product": "product",
    "Version": "version",
    "Platform": "platform",
    "Platform-Version": "platformVersion",
    "Device": "device",
    "Model": "model",
    "Device-Vendor": "deviceVendor",
    "Device-Name": "deviceName",
    "Marketplace": "marketplace",
  });
});

/** @internal */
export type SetChannelmapGlobals$Outbound = {
  accepts: string;
  "Client-Identifier"?: string | undefined;
  Product?: string | undefined;
  Version?: string | undefined;
  Platform?: string | undefined;
  "Platform-Version"?: string | undefined;
  Device?: string | undefined;
  Model?: string | undefined;
  "Device-Vendor"?: string | undefined;
  "Device-Name"?: string | undefined;
  Marketplace?: string | undefined;
};

/** @internal */
export const SetChannelmapGlobals$outboundSchema: z.ZodType<
  SetChannelmapGlobals$Outbound,
  z.ZodTypeDef,
  SetChannelmapGlobals
> = z.object({
  accepts: shared.Accepts$outboundSchema.default(shared.Accepts.ApplicationXml),
  clientIdentifier: z.string().optional(),
  product: z.string().optional(),
  version: z.string().optional(),
  platform: z.string().optional(),
  platformVersion: z.string().optional(),
  device: z.string().optional(),
  model: z.string().optional(),
  deviceVendor: z.string().optional(),
  deviceName: z.string().optional(),
  marketplace: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    clientIdentifier: "Client-Identifier",
    product: "Product",
    version: "Version",
    platform: "Platform",
    platformVersion: "Platform-Version",
    device: "Device",
    model: "Model",
    deviceVendor: "Device-Vendor",
    deviceName: "Device-Name",
    marketplace: "Marketplace",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SetChannelmapGlobals$ {
  /** @deprecated use `SetChannelmapGlobals$inboundSchema` instead. */
  export const inboundSchema = SetChannelmapGlobals$inboundSchema;
  /** @deprecated use `SetChannelmapGlobals$outboundSchema` instead. */
  export const outboundSchema = SetChannelmapGlobals$outboundSchema;
  /** @deprecated use `SetChannelmapGlobals$Outbound` instead. */
  export type Outbound = SetChannelmapGlobals$Outbound;
}

export function setChannelmapGlobalsToJSON(
  setChannelmapGlobals: SetChannelmapGlobals,
): string {
  return JSON.stringify(
    SetChannelmapGlobals$outboundSchema.parse(setChannelmapGlobals),
  );
}

export function setChannelmapGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<SetChannelmapGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SetChannelmapGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SetChannelmapGlobals' from JSON`,
  );
}

/** @internal */
export const SetChannelmapChannelMapping$inboundSchema: z.ZodType<
  SetChannelmapChannelMapping,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type SetChannelmapChannelMapping$Outbound = {};

/** @internal */
export const SetChannelmapChannelMapping$outboundSchema: z.ZodType<
  SetChannelmapChannelMapping$Outbound,
  z.ZodTypeDef,
  SetChannelmapChannelMapping
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SetChannelmapChannelMapping$ {
  /** @deprecated use `SetChannelmapChannelMapping$inboundSchema` instead. */
  export const inboundSchema = SetChannelmapChannelMapping$inboundSchema;
  /** @deprecated use `SetChannelmapChannelMapping$outboundSchema` instead. */
  export const outboundSchema = SetChannelmapChannelMapping$outboundSchema;
  /** @deprecated use `SetChannelmapChannelMapping$Outbound` instead. */
  export type Outbound = SetChannelmapChannelMapping$Outbound;
}

export function setChannelmapChannelMappingToJSON(
  setChannelmapChannelMapping: SetChannelmapChannelMapping,
): string {
  return JSON.stringify(
    SetChannelmapChannelMapping$outboundSchema.parse(
      setChannelmapChannelMapping,
    ),
  );
}

export function setChannelmapChannelMappingFromJSON(
  jsonString: string,
): SafeParseResult<SetChannelmapChannelMapping, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SetChannelmapChannelMapping$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SetChannelmapChannelMapping' from JSON`,
  );
}

/** @internal */
export const ChannelMappingByKey$inboundSchema: z.ZodType<
  ChannelMappingByKey,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type ChannelMappingByKey$Outbound = {};

/** @internal */
export const ChannelMappingByKey$outboundSchema: z.ZodType<
  ChannelMappingByKey$Outbound,
  z.ZodTypeDef,
  ChannelMappingByKey
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ChannelMappingByKey$ {
  /** @deprecated use `ChannelMappingByKey$inboundSchema` instead. */
  export const inboundSchema = ChannelMappingByKey$inboundSchema;
  /** @deprecated use `ChannelMappingByKey$outboundSchema` instead. */
  export const outboundSchema = ChannelMappingByKey$outboundSchema;
  /** @deprecated use `ChannelMappingByKey$Outbound` instead. */
  export type Outbound = ChannelMappingByKey$Outbound;
}

export function channelMappingByKeyToJSON(
  channelMappingByKey: ChannelMappingByKey,
): string {
  return JSON.stringify(
    ChannelMappingByKey$outboundSchema.parse(channelMappingByKey),
  );
}

export function channelMappingByKeyFromJSON(
  jsonString: string,
): SafeParseResult<ChannelMappingByKey, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChannelMappingByKey$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChannelMappingByKey' from JSON`,
  );
}

/** @internal */
export const SetChannelmapRequest$inboundSchema: z.ZodType<
  SetChannelmapRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  accepts: shared.Accepts$inboundSchema.default(shared.Accepts.ApplicationXml),
  "Client-Identifier": z.string().optional(),
  Product: z.string().optional(),
  Version: z.string().optional(),
  Platform: z.string().optional(),
  "Platform-Version": z.string().optional(),
  Device: z.string().optional(),
  Model: z.string().optional(),
  "Device-Vendor": z.string().optional(),
  "Device-Name": z.string().optional(),
  Marketplace: z.string().optional(),
  deviceId: z.number().int(),
  channelMapping: z.lazy(() => SetChannelmapChannelMapping$inboundSchema)
    .optional(),
  channelMappingByKey: z.lazy(() => ChannelMappingByKey$inboundSchema)
    .optional(),
  channelsEnabled: z.array(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "Client-Identifier": "clientIdentifier",
    "Product": "product",
    "Version": "version",
    "Platform": "platform",
    "Platform-Version": "platformVersion",
    "Device": "device",
    "Model": "model",
    "Device-Vendor": "deviceVendor",
    "Device-Name": "deviceName",
    "Marketplace": "marketplace",
  });
});

/** @internal */
export type SetChannelmapRequest$Outbound = {
  accepts: string;
  "Client-Identifier"?: string | undefined;
  Product?: string | undefined;
  Version?: string | undefined;
  Platform?: string | undefined;
  "Platform-Version"?: string | undefined;
  Device?: string | undefined;
  Model?: string | undefined;
  "Device-Vendor"?: string | undefined;
  "Device-Name"?: string | undefined;
  Marketplace?: string | undefined;
  deviceId: number;
  channelMapping?: SetChannelmapChannelMapping$Outbound | undefined;
  channelMappingByKey?: ChannelMappingByKey$Outbound | undefined;
  channelsEnabled?: Array<string> | undefined;
};

/** @internal */
export const SetChannelmapRequest$outboundSchema: z.ZodType<
  SetChannelmapRequest$Outbound,
  z.ZodTypeDef,
  SetChannelmapRequest
> = z.object({
  accepts: shared.Accepts$outboundSchema.default(shared.Accepts.ApplicationXml),
  clientIdentifier: z.string().optional(),
  product: z.string().optional(),
  version: z.string().optional(),
  platform: z.string().optional(),
  platformVersion: z.string().optional(),
  device: z.string().optional(),
  model: z.string().optional(),
  deviceVendor: z.string().optional(),
  deviceName: z.string().optional(),
  marketplace: z.string().optional(),
  deviceId: z.number().int(),
  channelMapping: z.lazy(() => SetChannelmapChannelMapping$outboundSchema)
    .optional(),
  channelMappingByKey: z.lazy(() => ChannelMappingByKey$outboundSchema)
    .optional(),
  channelsEnabled: z.array(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    clientIdentifier: "Client-Identifier",
    product: "Product",
    version: "Version",
    platform: "Platform",
    platformVersion: "Platform-Version",
    device: "Device",
    model: "Model",
    deviceVendor: "Device-Vendor",
    deviceName: "Device-Name",
    marketplace: "Marketplace",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SetChannelmapRequest$ {
  /** @deprecated use `SetChannelmapRequest$inboundSchema` instead. */
  export const inboundSchema = SetChannelmapRequest$inboundSchema;
  /** @deprecated use `SetChannelmapRequest$outboundSchema` instead. */
  export const outboundSchema = SetChannelmapRequest$outboundSchema;
  /** @deprecated use `SetChannelmapRequest$Outbound` instead. */
  export type Outbound = SetChannelmapRequest$Outbound;
}

export function setChannelmapRequestToJSON(
  setChannelmapRequest: SetChannelmapRequest,
): string {
  return JSON.stringify(
    SetChannelmapRequest$outboundSchema.parse(setChannelmapRequest),
  );
}

export function setChannelmapRequestFromJSON(
  jsonString: string,
): SafeParseResult<SetChannelmapRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SetChannelmapRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SetChannelmapRequest' from JSON`,
  );
}

/** @internal */
export const SetChannelmapResponse$inboundSchema: z.ZodType<
  SetChannelmapResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
  MediaContainerWithDevice: shared.MediaContainerWithDevice$inboundSchema
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
    "MediaContainerWithDevice": "mediaContainerWithDevice",
  });
});

/** @internal */
export type SetChannelmapResponse$Outbound = {
  ContentType: string;
  StatusCode: number;
  RawResponse: never;
  MediaContainerWithDevice?:
    | shared.MediaContainerWithDevice$Outbound
    | undefined;
};

/** @internal */
export const SetChannelmapResponse$outboundSchema: z.ZodType<
  SetChannelmapResponse$Outbound,
  z.ZodTypeDef,
  SetChannelmapResponse
> = z.object({
  contentType: z.string(),
  statusCode: z.number().int(),
  rawResponse: z.instanceof(Response).transform(() => {
    throw new Error("Response cannot be serialized");
  }),
  mediaContainerWithDevice: shared.MediaContainerWithDevice$outboundSchema
    .optional(),
}).transform((v) => {
  return remap$(v, {
    contentType: "ContentType",
    statusCode: "StatusCode",
    rawResponse: "RawResponse",
    mediaContainerWithDevice: "MediaContainerWithDevice",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SetChannelmapResponse$ {
  /** @deprecated use `SetChannelmapResponse$inboundSchema` instead. */
  export const inboundSchema = SetChannelmapResponse$inboundSchema;
  /** @deprecated use `SetChannelmapResponse$outboundSchema` instead. */
  export const outboundSchema = SetChannelmapResponse$outboundSchema;
  /** @deprecated use `SetChannelmapResponse$Outbound` instead. */
  export type Outbound = SetChannelmapResponse$Outbound;
}

export function setChannelmapResponseToJSON(
  setChannelmapResponse: SetChannelmapResponse,
): string {
  return JSON.stringify(
    SetChannelmapResponse$outboundSchema.parse(setChannelmapResponse),
  );
}

export function setChannelmapResponseFromJSON(
  jsonString: string,
): SafeParseResult<SetChannelmapResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SetChannelmapResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SetChannelmapResponse' from JSON`,
  );
}
