/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type SetItemPreferencesGlobals = {
  /**
   * Indicates the client accepts the indicated media types
   */
  accepts?: shared.Accepts | undefined;
  /**
   * An opaque identifier unique to the client
   */
  clientIdentifier?: string | undefined;
  /**
   * The name of the client product
   */
  product?: string | undefined;
  /**
   * The version of the client application
   */
  version?: string | undefined;
  /**
   * The platform of the client
   */
  platform?: string | undefined;
  /**
   * The version of the platform
   */
  platformVersion?: string | undefined;
  /**
   * A relatively friendly name for the client device
   */
  device?: string | undefined;
  /**
   * A potentially less friendly identifier for the device model
   */
  model?: string | undefined;
  /**
   * The device vendor
   */
  deviceVendor?: string | undefined;
  /**
   * A friendly name for the client
   */
  deviceName?: string | undefined;
  /**
   * The marketplace on which the client application is distributed
   */
  marketplace?: string | undefined;
};

export type SetItemPreferencesArgs = {};

export type SetItemPreferencesRequest = {
  /**
   * Indicates the client accepts the indicated media types
   */
  accepts?: shared.Accepts | undefined;
  /**
   * An opaque identifier unique to the client
   */
  clientIdentifier?: string | undefined;
  /**
   * The name of the client product
   */
  product?: string | undefined;
  /**
   * The version of the client application
   */
  version?: string | undefined;
  /**
   * The platform of the client
   */
  platform?: string | undefined;
  /**
   * The version of the platform
   */
  platformVersion?: string | undefined;
  /**
   * A relatively friendly name for the client device
   */
  device?: string | undefined;
  /**
   * A potentially less friendly identifier for the device model
   */
  model?: string | undefined;
  /**
   * The device vendor
   */
  deviceVendor?: string | undefined;
  /**
   * A friendly name for the client
   */
  deviceName?: string | undefined;
  /**
   * The marketplace on which the client application is distributed
   */
  marketplace?: string | undefined;
  ids: string;
  args?: SetItemPreferencesArgs | undefined;
};

export type SetItemPreferencesResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
};

/** @internal */
export const SetItemPreferencesGlobals$inboundSchema: z.ZodType<
  SetItemPreferencesGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  accepts: shared.Accepts$inboundSchema.default(shared.Accepts.ApplicationXml),
  "Client-Identifier": z.string().optional(),
  Product: z.string().optional(),
  Version: z.string().optional(),
  Platform: z.string().optional(),
  "Platform-Version": z.string().optional(),
  Device: z.string().optional(),
  Model: z.string().optional(),
  "Device-Vendor": z.string().optional(),
  "Device-Name": z.string().optional(),
  Marketplace: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "Client-Identifier": "clientIdentifier",
    "Product": "product",
    "Version": "version",
    "Platform": "platform",
    "Platform-Version": "platformVersion",
    "Device": "device",
    "Model": "model",
    "Device-Vendor": "deviceVendor",
    "Device-Name": "deviceName",
    "Marketplace": "marketplace",
  });
});

/** @internal */
export type SetItemPreferencesGlobals$Outbound = {
  accepts: string;
  "Client-Identifier"?: string | undefined;
  Product?: string | undefined;
  Version?: string | undefined;
  Platform?: string | undefined;
  "Platform-Version"?: string | undefined;
  Device?: string | undefined;
  Model?: string | undefined;
  "Device-Vendor"?: string | undefined;
  "Device-Name"?: string | undefined;
  Marketplace?: string | undefined;
};

/** @internal */
export const SetItemPreferencesGlobals$outboundSchema: z.ZodType<
  SetItemPreferencesGlobals$Outbound,
  z.ZodTypeDef,
  SetItemPreferencesGlobals
> = z.object({
  accepts: shared.Accepts$outboundSchema.default(shared.Accepts.ApplicationXml),
  clientIdentifier: z.string().optional(),
  product: z.string().optional(),
  version: z.string().optional(),
  platform: z.string().optional(),
  platformVersion: z.string().optional(),
  device: z.string().optional(),
  model: z.string().optional(),
  deviceVendor: z.string().optional(),
  deviceName: z.string().optional(),
  marketplace: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    clientIdentifier: "Client-Identifier",
    product: "Product",
    version: "Version",
    platform: "Platform",
    platformVersion: "Platform-Version",
    device: "Device",
    model: "Model",
    deviceVendor: "Device-Vendor",
    deviceName: "Device-Name",
    marketplace: "Marketplace",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SetItemPreferencesGlobals$ {
  /** @deprecated use `SetItemPreferencesGlobals$inboundSchema` instead. */
  export const inboundSchema = SetItemPreferencesGlobals$inboundSchema;
  /** @deprecated use `SetItemPreferencesGlobals$outboundSchema` instead. */
  export const outboundSchema = SetItemPreferencesGlobals$outboundSchema;
  /** @deprecated use `SetItemPreferencesGlobals$Outbound` instead. */
  export type Outbound = SetItemPreferencesGlobals$Outbound;
}

export function setItemPreferencesGlobalsToJSON(
  setItemPreferencesGlobals: SetItemPreferencesGlobals,
): string {
  return JSON.stringify(
    SetItemPreferencesGlobals$outboundSchema.parse(setItemPreferencesGlobals),
  );
}

export function setItemPreferencesGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<SetItemPreferencesGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SetItemPreferencesGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SetItemPreferencesGlobals' from JSON`,
  );
}

/** @internal */
export const SetItemPreferencesArgs$inboundSchema: z.ZodType<
  SetItemPreferencesArgs,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type SetItemPreferencesArgs$Outbound = {};

/** @internal */
export const SetItemPreferencesArgs$outboundSchema: z.ZodType<
  SetItemPreferencesArgs$Outbound,
  z.ZodTypeDef,
  SetItemPreferencesArgs
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SetItemPreferencesArgs$ {
  /** @deprecated use `SetItemPreferencesArgs$inboundSchema` instead. */
  export const inboundSchema = SetItemPreferencesArgs$inboundSchema;
  /** @deprecated use `SetItemPreferencesArgs$outboundSchema` instead. */
  export const outboundSchema = SetItemPreferencesArgs$outboundSchema;
  /** @deprecated use `SetItemPreferencesArgs$Outbound` instead. */
  export type Outbound = SetItemPreferencesArgs$Outbound;
}

export function setItemPreferencesArgsToJSON(
  setItemPreferencesArgs: SetItemPreferencesArgs,
): string {
  return JSON.stringify(
    SetItemPreferencesArgs$outboundSchema.parse(setItemPreferencesArgs),
  );
}

export function setItemPreferencesArgsFromJSON(
  jsonString: string,
): SafeParseResult<SetItemPreferencesArgs, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SetItemPreferencesArgs$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SetItemPreferencesArgs' from JSON`,
  );
}

/** @internal */
export const SetItemPreferencesRequest$inboundSchema: z.ZodType<
  SetItemPreferencesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  accepts: shared.Accepts$inboundSchema.default(shared.Accepts.ApplicationXml),
  "Client-Identifier": z.string().optional(),
  Product: z.string().optional(),
  Version: z.string().optional(),
  Platform: z.string().optional(),
  "Platform-Version": z.string().optional(),
  Device: z.string().optional(),
  Model: z.string().optional(),
  "Device-Vendor": z.string().optional(),
  "Device-Name": z.string().optional(),
  Marketplace: z.string().optional(),
  ids: z.string(),
  args: z.lazy(() => SetItemPreferencesArgs$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "Client-Identifier": "clientIdentifier",
    "Product": "product",
    "Version": "version",
    "Platform": "platform",
    "Platform-Version": "platformVersion",
    "Device": "device",
    "Model": "model",
    "Device-Vendor": "deviceVendor",
    "Device-Name": "deviceName",
    "Marketplace": "marketplace",
  });
});

/** @internal */
export type SetItemPreferencesRequest$Outbound = {
  accepts: string;
  "Client-Identifier"?: string | undefined;
  Product?: string | undefined;
  Version?: string | undefined;
  Platform?: string | undefined;
  "Platform-Version"?: string | undefined;
  Device?: string | undefined;
  Model?: string | undefined;
  "Device-Vendor"?: string | undefined;
  "Device-Name"?: string | undefined;
  Marketplace?: string | undefined;
  ids: string;
  args?: SetItemPreferencesArgs$Outbound | undefined;
};

/** @internal */
export const SetItemPreferencesRequest$outboundSchema: z.ZodType<
  SetItemPreferencesRequest$Outbound,
  z.ZodTypeDef,
  SetItemPreferencesRequest
> = z.object({
  accepts: shared.Accepts$outboundSchema.default(shared.Accepts.ApplicationXml),
  clientIdentifier: z.string().optional(),
  product: z.string().optional(),
  version: z.string().optional(),
  platform: z.string().optional(),
  platformVersion: z.string().optional(),
  device: z.string().optional(),
  model: z.string().optional(),
  deviceVendor: z.string().optional(),
  deviceName: z.string().optional(),
  marketplace: z.string().optional(),
  ids: z.string(),
  args: z.lazy(() => SetItemPreferencesArgs$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    clientIdentifier: "Client-Identifier",
    product: "Product",
    version: "Version",
    platform: "Platform",
    platformVersion: "Platform-Version",
    device: "Device",
    model: "Model",
    deviceVendor: "Device-Vendor",
    deviceName: "Device-Name",
    marketplace: "Marketplace",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SetItemPreferencesRequest$ {
  /** @deprecated use `SetItemPreferencesRequest$inboundSchema` instead. */
  export const inboundSchema = SetItemPreferencesRequest$inboundSchema;
  /** @deprecated use `SetItemPreferencesRequest$outboundSchema` instead. */
  export const outboundSchema = SetItemPreferencesRequest$outboundSchema;
  /** @deprecated use `SetItemPreferencesRequest$Outbound` instead. */
  export type Outbound = SetItemPreferencesRequest$Outbound;
}

export function setItemPreferencesRequestToJSON(
  setItemPreferencesRequest: SetItemPreferencesRequest,
): string {
  return JSON.stringify(
    SetItemPreferencesRequest$outboundSchema.parse(setItemPreferencesRequest),
  );
}

export function setItemPreferencesRequestFromJSON(
  jsonString: string,
): SafeParseResult<SetItemPreferencesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SetItemPreferencesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SetItemPreferencesRequest' from JSON`,
  );
}

/** @internal */
export const SetItemPreferencesResponse$inboundSchema: z.ZodType<
  SetItemPreferencesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
  });
});

/** @internal */
export type SetItemPreferencesResponse$Outbound = {
  ContentType: string;
  StatusCode: number;
  RawResponse: never;
};

/** @internal */
export const SetItemPreferencesResponse$outboundSchema: z.ZodType<
  SetItemPreferencesResponse$Outbound,
  z.ZodTypeDef,
  SetItemPreferencesResponse
> = z.object({
  contentType: z.string(),
  statusCode: z.number().int(),
  rawResponse: z.instanceof(Response).transform(() => {
    throw new Error("Response cannot be serialized");
  }),
}).transform((v) => {
  return remap$(v, {
    contentType: "ContentType",
    statusCode: "StatusCode",
    rawResponse: "RawResponse",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SetItemPreferencesResponse$ {
  /** @deprecated use `SetItemPreferencesResponse$inboundSchema` instead. */
  export const inboundSchema = SetItemPreferencesResponse$inboundSchema;
  /** @deprecated use `SetItemPreferencesResponse$outboundSchema` instead. */
  export const outboundSchema = SetItemPreferencesResponse$outboundSchema;
  /** @deprecated use `SetItemPreferencesResponse$Outbound` instead. */
  export type Outbound = SetItemPreferencesResponse$Outbound;
}

export function setItemPreferencesResponseToJSON(
  setItemPreferencesResponse: SetItemPreferencesResponse,
): string {
  return JSON.stringify(
    SetItemPreferencesResponse$outboundSchema.parse(setItemPreferencesResponse),
  );
}

export function setItemPreferencesResponseFromJSON(
  jsonString: string,
): SafeParseResult<SetItemPreferencesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SetItemPreferencesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SetItemPreferencesResponse' from JSON`,
  );
}
