/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { collectionsCreateCollection } from "../funcs/collectionsCreateCollection.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import { unwrapAsync } from "./types/fp.js";

export class Collections extends ClientSDK {
  /**
   * Create collection
   *
   * @remarks
   * Create a collection in the library
   */
  async createCollection(
    request: operations.CreateCollectionRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateCollectionResponse> {
    return unwrapAsync(collectionsCreateCollection(
      this,
      request,
      options,
    ));
  }
}
