workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    plexapi:
        inputs:
            - location: https://raw.githubusercontent.com/LukeHagar/plex-api-spec/refs/heads/main/plex-api-spec.yaml
        registry:
            location: registry.speakeasyapi.dev/plexapi/plexapi/plexapi
targets:
    plexjs:
        target: typescript
        source: plexapi
        publish:
            npm:
                token: $npm_token
        codeSamples:
            output: codeSamples.yaml
            registry:
                location: registry.speakeasyapi.dev/plexapi/plexapi/code-samples-typescript-plexjs
            labelOverride:
                fixedValue: PlexJS
