workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-source:
        inputs:
            - location: registry.speakeasyapi.dev/plexapi/plexapi/plex-api:main
targets:
    plexjs:
        target: typescript
        source: my-source
        publish:
            npm:
                token: $npm_token
        codeSamples:
            output: codeSamples.yaml
            registry:
                location: registry.speakeasyapi.dev/plexapi/plexapi/code-samples-typescript-plexjs
