workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-source:
        inputs:
            - location: https://raw.githubusercontent.com/LukeHagar/plex-api-spec/main/plex-media-server-spec-dereferenced.yaml
        registry:
            location: registry.speakeasyapi.dev/lukehagar/lukehagar/my-source
targets:
    plexjs:
        target: typescript
        source: my-source
        publish:
            npm:
                token: $NPM_TOKEN
        codeSamples:
            output: codeSamples.yaml
            registry:
                location: registry.speakeasyapi.dev/lukehagar/lukehagar/code-samples-typescript-plexjs
