/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";

/**
 * Protocol to filter discovery.
 */
export enum DiscoverDevicesProtocol {
  Stream = "stream",
  Download = "download",
  Livetv = "livetv",
}

export type DiscoverDevicesRequest = {
  /**
   * Protocol to filter discovery.
   */
  protocol?: DiscoverDevicesProtocol | undefined;
  /**
   * Targeted grabber identifier.
   */
  grabberIdentifier?: string | undefined;
};

/** @internal */
export const DiscoverDevicesProtocol$outboundSchema: z.ZodEnum<
  typeof DiscoverDevicesProtocol
> = z.enum(DiscoverDevicesProtocol);

/** @internal */
export type DiscoverDevicesRequest$Outbound = {
  protocol?: string | undefined;
  grabberIdentifier?: string | undefined;
};

/** @internal */
export const DiscoverDevicesRequest$outboundSchema: z.ZodType<
  DiscoverDevicesRequest$Outbound,
  DiscoverDevicesRequest
> = z.object({
  protocol: DiscoverDevicesProtocol$outboundSchema.optional(),
  grabberIdentifier: z.string().optional(),
});

export function discoverDevicesRequestToJSON(
  discoverDevicesRequest: DiscoverDevicesRequest,
): string {
  return JSON.stringify(
    DiscoverDevicesRequest$outboundSchema.parse(discoverDevicesRequest),
  );
}
