export type TaskName =
  | 'BackupDatabase'
  | 'BuildGracenoteCollections'
  | 'CheckForUpdates'
  | 'CleanOldBundles'
  | 'CleanOldCacheFiles'
  | 'DeepMediaAnalysis'
  | 'GenerateAutoTags'
  | 'GenerateChapterThumbs'
  | 'GenerateMediaIndexFiles'
  | 'OptimizeDatabase'
  | 'RefreshLibraries'
  | 'RefreshLocalMedia'
  | 'RefreshPeriodicMetadata'
  | 'UpgradeMediaAnalysis';
