/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * `MediaContainer` is the root element of most Plex API responses. It serves as a generic container for various types of content (Metadata, Hubs, Directories, etc.) and includes pagination information (offset, size, totalSize) when applicable.
 *
 * @remarks
 * Common attributes: - identifier: Unique identifier for this container - size: Number of items in this response page - totalSize: Total number of items available (for pagination) - offset: Starting index of this page (for pagination)
 * The container often "hoists" common attributes from its children. For example, if all tracks in a container share the same album title, the `parentTitle` attribute may appear on the MediaContainer rather than being repeated on each track.
 */
export type MediaContainerWithStatusMediaContainer = {
  identifier?: string | undefined;
  /**
   * The offset of where this container page starts among the total objects available. Also provided in the `X-Plex-Container-Start` header.
   */
  offset?: number | undefined;
  size?: number | undefined;
  /**
   * The total size of objects available. Also provided in the `X-Plex-Container-Total-Size` header.
   */
  totalSize?: number | undefined;
  /**
   * A status indicator. If present and non-zero, indicates an error
   */
  status?: number | undefined;
};

export type MediaContainerWithStatus = {
  mediaContainer?: MediaContainerWithStatusMediaContainer | undefined;
};

/** @internal */
export const MediaContainerWithStatusMediaContainer$inboundSchema: z.ZodType<
  MediaContainerWithStatusMediaContainer,
  unknown
> = z.object({
  identifier: types.optional(types.string()),
  offset: types.optional(types.number()),
  size: types.optional(types.number()),
  totalSize: types.optional(types.number()),
  status: types.optional(types.number()),
});

export function mediaContainerWithStatusMediaContainerFromJSON(
  jsonString: string,
): SafeParseResult<MediaContainerWithStatusMediaContainer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      MediaContainerWithStatusMediaContainer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MediaContainerWithStatusMediaContainer' from JSON`,
  );
}

/** @internal */
export const MediaContainerWithStatus$inboundSchema: z.ZodType<
  MediaContainerWithStatus,
  unknown
> = z.object({
  MediaContainer: types.optional(
    z.lazy(() => MediaContainerWithStatusMediaContainer$inboundSchema),
  ),
}).transform((v) => {
  return remap$(v, {
    "MediaContainer": "mediaContainer",
  });
});

export function mediaContainerWithStatusFromJSON(
  jsonString: string,
): SafeParseResult<MediaContainerWithStatus, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MediaContainerWithStatus$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MediaContainerWithStatus' from JSON`,
  );
}
