name: "Build TypeScript SDK"

on:
  workflow_dispatch:

jobs:
  push_spec_workflow:
    name: Build TypeScript SDK
    runs-on: ubuntu-latest
    steps:
      # Checkout the master branch request to run rsync
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      # Checkout the main branch of api-specs
      - name: Checkout API Specs Repo
        uses: actions/checkout@v3
        with:
          repository: lukehagar/plex-api-spec
          path: api-specs
          ref: main

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Build TS SDK
        id: buildTS
        run: |
          rm -rf plexjs/
          java -jar openapi-generator-cli.jar generate -i api-specs/referenced/plex-api-spec.yaml -g typescript-axios -o plexjs/ --global-property skipFormModel=false --config config.yaml

      - name: Run npm install and build Typescript SDK
        id: buildSDK
        if: steps.buildTS.outcome == 'success'
        run: |
          cd plexjs
          npm install
          npm run build
