name: Release Checks

on:
  push:
    branches:
      - main

jobs:
  github-publish:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository & Submo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm install

      # TODO: Finish fixing eslint issues
      # - name: Run ESLint check
      #   run: npm run lint:ci

      - name: Run Test & Coverage check
        run: npm run test
        
