name: Speakeasy Tagging
permissions:
    checks: write
    contents: write
    pull-requests: write
    statuses: write
"on":
    push:
        branches:
            - main
        paths: []
    workflow_dispatch: {}
jobs:
    tag:
        uses: speakeasy-api/sdk-generation-action/.github/workflows/tag.yaml@v15
        with:
            registry_tags: main
        secrets:
            github_access_token: ${{ secrets.GITHUB_TOKEN }}
            speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
