name: "Test open api generator version"

run-name: "Test open api generator version ${{ github.event.inputs.version }}"

on:
  workflow_dispatch:
    inputs:
      version:
        description: The version of the OpenAPI Generator to test

jobs:
  push_spec_workflow:
    name: Build TypeScript SDK
    runs-on: ubuntu-latest
    steps:
      # Checkout the master branch request to run rsync
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      # Checkout the main branch of api-specs
      - name: Checkout API Specs Repo
        uses: actions/checkout@v3
        with:
          repository: lukehagar/plex-api-spec
          path: api-specs
          ref: main

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install OpenAPI Generator
        run: |
          wget https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/${{ github.event.inputs.version }}/openapi-generator-cli-${{ github.event.inputs.version }}.jar -O openapi-generator-cli.jar

      - name: Build PMS SDK
        id: buildPMS
        run: |
          rm -rf plexjs/pms
          java -jar openapi-generator-cli.jar generate -i api-specs/pms/pms-spec.yaml -g typescript-axios -o plexjs/pms --config sdk-resources/pms-config-test.yaml

      - name: Build PTV SDK
        id: buildPTV
        run: |
          rm -rf plexjs/plextv
          java -jar openapi-generator-cli.jar generate -i api-specs/plextv/plextv-spec.yaml -g typescript-axios -o plexjs/plextv --config sdk-resources/plextv-config-test.yaml

      - name: Archive test build
        uses: actions/upload-artifact@v3
        with:
          name: OAG-${{ github.event.inputs.version }}-test-build
          path: |
            plexjs/pms
            plexjs/plextv

      - name: Run npm install and build Typescript SDK
        id: testPMS
        if: steps.buildPMS.outcome == 'success'
        run: |
          cd plexjs/pms
          npm install
          npm run build

      - name: Run npm install and build Typescript SDK
        id: testPTV
        if: steps.buildPTV.outcome == 'success'
        run: |
          cd plexjs/plextv
          npm install
          npm run build
